<template>
  <main class="bidding-workbench" v-loading="loading">
    <header class="page-heading"><div><el-button link type="primary" @click="router.push('/bidding')">← {{ l('项目列表','Projects') }}</el-button><h1>{{ project?.name || l('投标工作台','Bidding workbench') }}</h1></div><div class="heading-actions"><el-button v-if="project && capabilities?.canWrite" type="primary" @click="handoffOpen=true">{{ l('接收售前版本','Receive presales version') }}</el-button><el-button v-if="project" type="primary" plain @click="taskDrawer=true">{{ l('任务记录','Task records') }}</el-button><el-button v-if="canApproveProject" type="primary" plain @click="ownerDialog=true">{{ l('项目档案','Project settings') }}</el-button><el-button type="primary" plain @click="load">{{ l('刷新','Refresh') }}</el-button></div></header>
    <el-alert v-if="unavailable" :title="l('投标模块尚未启用。','Bidding is not enabled.')" type="info" :closable="false" />
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><template #default><p v-if="conflict">{{ l('版本已变化，当前草稿已保留。刷新并核对后再提交。','The record changed. Your draft is retained. Refresh and compare before submitting.') }}</p><el-button type="primary" size="small" @click="load">{{ l('重新加载','Reload') }}</el-button></template></el-alert>
    <el-alert v-if="conflict && projectDraftChanged" :title="l('服务器版本已刷新；您的项目档案草稿仍保留。','The server version is refreshed; your project settings draft is retained.')" type="warning" :closable="false" />
    <el-alert v-if="capabilities && !capabilities.canWrite" :title="l('只读访问：您可以查看项目和证据。','Read only: you can view the project and evidence.')" type="info" :closable="false" />
    <template v-if="project && capabilities?.enabled">
      <el-tabs v-model="tab" class="workbench-tabs" :before-leave="beforeTabLeave">
        <el-tab-pane :label="l('概览','Overview')" name="overview"><BiddingOverview :project="project" :members="members" :employees="employees" :can-approve="canApproveProject" :saving="saving" :error="employeeError" @save="assignEmployees" /></el-tab-pane>
        <el-tab-pane :label="l('文件与来源','Sources')" name="sources"><BiddingSources :project="project" :sources="sources" :source-set="sourceSet" :loading="sourcesLoading" :can-write="!!capabilities.canWrite" :can-approve="canApproveProject" :analyst-ready="analystReady" :active-analysis="activeAnalysis" :dispatching="dispatching" @changed="refreshSources" @preview="preview" @tasks="taskDrawer=true" @dispatch="dispatchAnalysis" @retry-read="retrySource" /><BiddingMaterials :workspace-id="workspace.currentWorkspaceId || ''" :project="project" :items="materials" :loading="materialsLoading" :can-write="!!capabilities.canWrite" :busy="p2Busy" :error="materialsError" @bind="bindMaterial" @changed="refreshMaterials" /></el-tab-pane>
        <el-tab-pane :label="l('解析结果','Analysis')" name="analysis"><BiddingChangeImpact :view="changeImpact" :busy="changeImpactLoading" :error="changeImpactError" :can-confirm="canApproveProject" @refresh="refreshChangeImpact" @confirm="confirmChangeImpact" /><BiddingAnalysis :analysis="analysis" :can-write="!!capabilities.canWrite" :can-approve="canApproveProject" @evidence="openEvidence" @edit="editAnalysis" @confirm="confirmAnalysis" /></el-tab-pane>
        <el-tab-pane :label="l('目录规划','Outline')" name="outline"><BiddingOutline ref="outlineSurface" :view="outline" :project-ref="project.ref" :saved-ref="outlineSavedRef" :clear-token="outlineClearToken" :can-write="!!capabilities.canWrite" :can-approve="canApproveProject" :can-dispatch="canDispatchOutline" :busy="p2Busy" :dispatching="outlineDispatching" :saving="outlineSaving" :confirming="outlineConfirming" :error="outlineError" @command="outlineCommand" /></el-tab-pane>
        <el-tab-pane :label="l('技术标写作','Writing')" name="writing"><BiddingWriting ref="writingSurface" :view="writing" :can-write="!!capabilities.canWrite" :can-dispatch="!!outline.confirmed && !!capabilities.canWrite" :busy="p2Busy" :dispatching-chapter-ids="dispatchingChapterIds" :error="writingError" :saved-token="writingSavedToken" :clear-token="writingClearToken" @dispatch="dispatchWriting" @command="writingCommand" @retry-task="retryWritingTask" @assemble="assembleManuscript" /></el-tab-pane>
        <el-tab-pane :label="l('审核与导出','Review')" name="review"><div class="review-export-layout"><BiddingReview :view="reviewView" :chapters="writing.chapters.map(item=>({id:item.chapterId,title:item.title}))" :can-write="!!capabilities.canWrite" :can-approve="canApproveProject" :can-resolve-todo="canApproveProject" :reviewer-ready="reviewerReady" :busy="reviewBusy" @refresh="refreshReviewAndArtifacts" @dispatch="dispatchReview" @fix="targetFinding" @resolve="openFindingDecision" @classify="openTodoClassification" @resolve-todo="openTodoResolution" @evidence="openEvidence" @chapter="focusChapter"/><BiddingArtifacts :templates="templates" :artifacts="artifacts" :loading="artifactLoading" :busy="exportBusy" :can-write="!!capabilities.canWrite" :can-approve="canApproveProject" @refresh="refreshReviewAndArtifacts" @prepare="prepareExport" @generate="generateExport" @download="downloadArtifact" @approval-context="openApproval" /></div></el-tab-pane>
      </el-tabs>
    </template>
    <el-dialog v-model="ownerDialog" :title="l('项目档案','Project settings')" width="min(560px,94vw)" :close-on-click-modal="false">
      <el-form label-position="right" label-width="110px"><el-form-item :label="l('项目名称','Project name')"><el-input v-model="projectDraft.name" maxlength="200" /></el-form-item><el-form-item :label="l('标段','Lot')"><el-input v-model="projectDraft.lotName" maxlength="200" /></el-form-item><el-form-item :label="l('负责人','Owner')"><el-select v-model="projectDraft.ownerId" filterable :loading="membersLoading" :disabled="membersLoading || !members.length"><el-option v-for="member in members" :key="String(member.userId)" :label="memberLabel(member)" :value="String(member.userId)" /></el-select></el-form-item></el-form>
      <template #footer><el-button @click="ownerDialog=false">{{ l('取消','Cancel') }}</el-button><el-button type="primary" :loading="saving" :disabled="!projectDraft.name.trim()||!projectDraft.lotName.trim()" @click="saveProject">{{ l('保存','Save') }}</el-button></template>
    </el-dialog>
    <el-dialog v-model="decisionOpen" :title="decisionTitle" width="min(600px,94vw)" :close-on-click-modal="false"><el-form label-position="top"><el-form-item v-if="decisionAction==='CLASSIFY_HUMAN_TODO'" :label="l('是否影响技术标','Affects technical proposal')"><el-radio-group v-model="decisionAffectsTechnical"><el-radio :value="true">{{ l('影响技术标','Affects technical proposal') }}</el-radio><el-radio :value="false">{{ l('仅商务事项','Business only') }}</el-radio></el-radio-group></el-form-item><el-form-item v-if="decisionNeedsEvidence" :label="l('依据来源','Evidence source')"><el-select v-model="decisionEvidenceKey" filterable :placeholder="l('选择已授权来源','Select an authorized source')"><el-option v-for="option in evidenceOptions" :key="option.key" :label="option.label" :value="option.key" /></el-select></el-form-item><el-form-item v-if="decisionNeedsEvidence" :label="l('来源段落','Source passage')"><el-select v-model="decisionBlockId" :placeholder="l('选择原文段落','Select a source passage')"><el-option v-for="block in selectedEvidenceBlocks" :key="block.id" :label="`${block.locator} · ${block.text.slice(0,90)}`" :value="block.id" /></el-select></el-form-item><el-form-item :label="l('处理说明','Reason')"><el-input v-model="decisionReason" type="textarea" :rows="3" maxlength="2000" /></el-form-item></el-form><template #footer><el-button @click="decisionOpen=false">{{ l('取消','Cancel') }}</el-button><el-button type="primary" :loading="reviewBusy" :disabled="!decisionReason.trim() || (decisionNeedsEvidence && !decisionBlockId)" @click="submitReviewDecision">{{ l('提交','Submit') }}</el-button></template></el-dialog>
    <BiddingHandoffDialog v-model="handoffOpen" :workspace-id="workspace.currentWorkspaceId || ''" :project="project!" :busy="p2Busy" @receive="receiveHandoff" v-if="project" />
    <BiddingApprovalDialog v-model="approvalOpen" :context="approvalContext" :busy="approvalBusy" :conflict="approvalConflict" @approve="approveArtifact" />
    <el-dialog v-model="previewOpen" :title="previewSource?.filename || l('来源文本','Source text')" width="min(900px,95vw)"><el-table :data="previewSource?.blocks || []" max-height="65vh"><el-table-column prop="locator" :label="l('位置','Location')" min-width="180"/><el-table-column prop="text" :label="l('原文','Source text')" min-width="420" show-overflow-tooltip/></el-table></el-dialog>
    <BiddingTaskDrawer v-model="taskDrawer" :workspace-id="workspace.currentWorkspaceId || ''" :project="project!" :can-write="!!capabilities?.canWrite" v-if="project" @changed="refreshAll" @access-denied="handleReadFailure" />
    <BiddingEvidenceDrawer v-model="evidenceOpen" :workspace-id="workspace.currentWorkspaceId || ''" :project-id="project?.id || ''" :source-ref="evidenceRef" />
  </main>
</template>
<script setup lang="ts">
import { vLoading } from 'element-plus/es/components/loading/index.mjs'
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate, useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ElMessageBox } from 'element-plus'
import { useWorkspaceStore } from '@/stores/useWorkspaceStore'
import { biddingApi } from '../api/biddingApi'
import type { AnalysisView, ArtifactApprovalContext, ArtifactMetadata, BiddingHumanTodo, BiddingMaterial, BiddingReviewFinding, BiddingReviewView, Capabilities, ChangeImpactConfirmationPayload, ChangeImpactView, Employee, ExportTemplate, Member, OutlineView, Project, Ref, Source, WritingView } from '../api/types'
import { apiUnavailable, isConflict, isCurrentRequest, operationId } from '../shared/state'
import BiddingOverview from '../components/BiddingOverview.vue'
import BiddingSources from '../components/BiddingSources.vue'
import BiddingAnalysis from '../components/BiddingAnalysis.vue'
import BiddingTaskDrawer from '../components/BiddingTaskDrawer.vue'
import BiddingEvidenceDrawer from '../components/BiddingEvidenceDrawer.vue'
import BiddingHandoffDialog from '../components/BiddingHandoffDialog.vue'
import BiddingMaterials from '../components/BiddingMaterials.vue'
import BiddingChangeImpact from '../components/BiddingChangeImpact.vue'
import BiddingOutline from '../components/BiddingOutline.vue'
import BiddingWriting from '../components/BiddingWriting.vue'
import BiddingReview from '../components/BiddingReview.vue'
import BiddingArtifacts from '../components/BiddingArtifacts.vue'
import BiddingApprovalDialog from '../components/BiddingApprovalDialog.vue'
const route=useRoute(),router=useRouter(),workspace=useWorkspaceStore(),{locale}=useI18n(),l=(zh:string,en:string)=>String(locale.value).startsWith('zh')?zh:en
const projectId=computed(()=>String(route.params.id||'')),project=ref<Project>(),capabilities=ref<Capabilities>(),members=ref<Member[]>([]),employees=ref<Employee[]>([]),sources=ref<Source[]>([]),sourceSet=ref<{ref?:Project['ref']}|null>(null),analysis=ref<AnalysisView>({groups:[]})
const loading=ref(false),sourcesLoading=ref(false),membersLoading=ref(false),saving=ref(false),dispatching=ref(false),error=ref(''),employeeError=ref(''),conflict=ref(false),unavailable=ref(false),tab=ref('overview'),taskDrawer=ref(false),ownerDialog=ref(false),previewOpen=ref(false),previewSource=ref<Source>(),evidenceOpen=ref(false),evidenceRef=ref<Record<string,unknown>>()
const materials=ref<BiddingMaterial[]>([]),outline=ref<OutlineView>({candidates:[]}),writing=ref<WritingView>({chapters:[]}),changeImpact=ref<ChangeImpactView>({events:[],formalBlocked:false}),materialsLoading=ref(false),materialsError=ref(''),outlineError=ref(''),writingError=ref(''),changeImpactError=ref(''),changeImpactLoading=ref(false),p2Busy=ref(false),outlineDispatching=ref(false),outlineSaving=ref(false),outlineConfirming=ref(false),outlineSavedRef=ref<Ref>(),outlineClearToken=ref(0),writingClearToken=ref(0),handoffOpen=ref(false),dispatchingChapterIds=ref<string[]>([]),writingSavedToken=ref(0)
const reviewView=ref<BiddingReviewView>({status:'NOT_ASSEMBLED',tasks:[],findings:[],humanTodos:[]}),templates=ref<ExportTemplate[]>([]),artifacts=ref<ArtifactMetadata[]>([]),reviewBusy=ref(false),artifactLoading=ref(false),exportBusy=ref(false),approvalBusy=ref(false),approvalOpen=ref(false),approvalContext=ref<ArtifactApprovalContext>(),approvalConflict=ref(false),decisionOpen=ref(false),decisionAction=ref(''),decisionReason=ref(''),decisionEvidenceKey=ref(''),decisionBlockId=ref(''),decisionAffectsTechnical=ref(true),activeFinding=ref<BiddingReviewFinding>(),activeTodo=ref<BiddingHumanTodo>()
const outlineSurface=ref<InstanceType<typeof BiddingOutline>>(),writingSurface=ref<InstanceType<typeof BiddingWriting>>()
const projectDraft=reactive({name:'',lotName:'',ownerId:''})
let controller:AbortController|undefined,unregister:(()=>void)|undefined,p2RequestToken=0
const downloadUrls=new Set<string>()
const analystReady=computed(()=>!!project.value?.bindings?.analyst?.agentId&&!!project.value.bindings.analyst.skillPins?.length)
const canApproveProject=computed(()=>!!project.value?.capabilities?.canApprove)
const reviewerReady=computed(()=>{const reviewer=project.value?.bindings?.reviewer,writer=project.value?.bindings?.writer;return !!reviewer?.agentId&&reviewer.agentId!==writer?.agentId&&!!reviewer.skillPins?.length})
const activeAnalysis=computed(()=>analysis.value.groups.some(group=>['QUEUED','RUNNING'].includes(group.status)))
const canDispatchOutline=computed(()=>!!analysis.value.baseline&&!!project.value?.bindings?.writer?.agentId&&!!project.value.bindings.writer.skillPins?.length)
const projectDraftChanged=computed(()=>!!project.value&&(projectDraft.name!==project.value.name||projectDraft.lotName!==project.value.lotName||projectDraft.ownerId!==String(project.value.ownerId)))
const decisionNeedsEvidence=computed(()=>decisionAction.value==='DISMISS_WITH_EVIDENCE'||decisionAction.value==='CLASSIFY_HUMAN_TODO'||decisionAction.value==='RESOLVE_HUMAN_TODO')
const decisionTitle=computed(()=>decisionAction.value==='CLASSIFY_HUMAN_TODO'?l('判断技术影响','Classify technical impact'):decisionAction.value==='RESOLVE_HUMAN_TODO'?l('处理商务待办','Resolve business item'):decisionAction.value==='DEFER_SUGGESTION'?l('暂不采纳此建议','Defer suggestion'):l('处置审核发现','Resolve finding'))
const evidenceOptions=computed(()=>sources.value.map(source=>({key:`${source.sourceId}:${source.version}`,label:source.filename,source})))
const selectedEvidenceSource=computed(()=>evidenceOptions.value.find(item=>item.key===decisionEvidenceKey.value)?.source)
const selectedEvidenceBlocks=computed(()=>selectedEvidenceSource.value?.blocks||[])
function memberLabel(member:Member){return member.nickname||member.username||l('成员不可用','Member unavailable')}
function assertCurrent(ws:string,id:string,signal:AbortSignal){return !signal.aborted&&isCurrentRequest(ws,id,workspace.currentWorkspaceId||'',projectId.value)}
function responseStatus(cause:unknown){return cause&&typeof cause==='object'&&'response'in cause?(cause as {response?:{status?:number}}).response?.status:undefined}
function clearReviewState(){reviewView.value={status:'NOT_ASSEMBLED',tasks:[],findings:[],humanTodos:[]};templates.value=[];artifacts.value=[];reviewBusy.value=false;artifactLoading.value=false;exportBusy.value=false;approvalBusy.value=false;approvalContext.value=undefined;approvalOpen.value=false;approvalConflict.value=false;decisionOpen.value=false;decisionReason.value='';decisionBlockId.value='';decisionEvidenceKey.value='';activeFinding.value=undefined;activeTodo.value=undefined;for(const url of downloadUrls)URL.revokeObjectURL(url);downloadUrls.clear()}
function clearProjectData(){p2RequestToken++;p2Busy.value=false;project.value=undefined;capabilities.value=undefined;members.value=[];employees.value=[];sources.value=[];sourceSet.value=null;analysis.value={groups:[]};materials.value=[];outline.value={candidates:[]};writing.value={chapters:[]};changeImpact.value={events:[],formalBlocked:false};clearReviewState();materialsError.value='';outlineError.value='';writingError.value='';changeImpactError.value='';loading.value=false;sourcesLoading.value=false;materialsLoading.value=false;changeImpactLoading.value=false;outlineDispatching.value=false;outlineSaving.value=false;outlineConfirming.value=false;outlineSavedRef.value=undefined;outlineClearToken.value++;writingClearToken.value++;outlineSurface.value?.clearSensitiveDraft();writingSurface.value?.clearSensitiveDraft();dispatchingChapterIds.value=[];taskDrawer.value=false;previewOpen.value=false;previewSource.value=undefined;evidenceOpen.value=false;evidenceRef.value=undefined;ownerDialog.value=false;handoffOpen.value=false;conflict.value=false;projectDraft.name='';projectDraft.lotName='';projectDraft.ownerId=''}
function handleReadFailure(cause:unknown){const status=responseStatus(cause);if(![401,403,404,410].includes(status||0))return false;controller?.abort();clearProjectData();unavailable.value=status===404;error.value=status===401||status===403?l('您已无权访问此项目。','You no longer have access to this project.'):status===410?l('此项目已不再可用。','This project is no longer available.'):'';return true}
async function load(){const ws=workspace.currentWorkspaceId||'',id=projectId.value;const sameProject=project.value?.id===id&&project.value.workspaceId===ws;const preserveDraft=sameProject&&projectDraftChanged.value;controller?.abort();controller=new AbortController();const current=controller,signal=current.signal;if(!sameProject)clearProjectData();error.value='';if(!preserveDraft)conflict.value=false;unavailable.value=false;if(!ws){error.value=l('请选择工作区。','Select a workspace.');return}loading.value=true
try{const caps=await biddingApi.capabilities(ws,signal);if(!assertCurrent(ws,id,signal))return;capabilities.value=caps;if(!caps.enabled){clearProjectData();unavailable.value=true;return}const [detail,memberRows,employeeRows]=await Promise.all([biddingApi.get(ws,id,signal),biddingApi.members(ws,signal),biddingApi.employees(ws,signal)]);if(!assertCurrent(ws,id,signal))return;project.value=detail;members.value=memberRows.map(m=>({...m,userId:String(m.userId)}));employees.value=employeeRows.map(e=>({...e,id:String(e.id)}));if(!preserveDraft){projectDraft.name=detail.name;projectDraft.lotName=detail.lotName;projectDraft.ownerId=String(detail.ownerId)}employeeError.value='';await Promise.all([refreshSources(),refreshAnalysis(),refreshP2()]);if(tab.value==='review')await refreshReviewAndArtifacts()}
catch(cause){if(!signal.aborted&&!handleReadFailure(cause)){unavailable.value=apiUnavailable(cause);error.value=unavailable.value?'':l('项目加载失败。','Could not load project.')}}finally{if(!signal.aborted)loading.value=false}}
async function refreshSources(){const ws=workspace.currentWorkspaceId||'',id=projectId.value;if(!ws||!id)return;sourcesLoading.value=true;const signal=controller?.signal;try{const [rows,head]=await Promise.all([biddingApi.sources(ws,id,signal),biddingApi.sourceSetHead(ws,id,signal)]);if(!signal?.aborted&&project.value?.id===id&&project.value.workspaceId===ws&&isCurrentRequest(ws,id,workspace.currentWorkspaceId||'',projectId.value)){sources.value=rows;sourceSet.value=head}}catch(cause){if(!signal?.aborted&&!handleReadFailure(cause))error.value=l('文件来源读取失败。','Could not load sources.')}finally{if(!signal?.aborted)sourcesLoading.value=false}}
async function refreshAnalysis(){const ws=workspace.currentWorkspaceId||'',id=projectId.value;if(!ws||!id)return;const signal=controller?.signal;try{const result=await biddingApi.analysis(ws,id,signal);if(!signal?.aborted&&project.value?.id===id&&project.value.workspaceId===ws&&isCurrentRequest(ws,id,workspace.currentWorkspaceId||'',projectId.value))analysis.value=result}catch(cause){if(!signal?.aborted&&!handleReadFailure(cause))error.value=l('解析结果无法读取，来源可能已变化或撤权。','Analysis is unavailable; a source may have changed or access may have been withdrawn.')}}
function accessDenied(cause:unknown){const status=responseStatus(cause);return status===401||status===403||status===404||status===410}
function p2ScopeCurrent(ws:string,id:string,signal?:AbortSignal){return !!signal&&!signal.aborted&&assertCurrent(ws,id,signal)&&project.value?.id===id&&project.value.workspaceId===ws}
function clearDeniedP2Scope(cause:unknown,ws:string,id:string,signal?:AbortSignal){if(!accessDenied(cause)||!p2ScopeCurrent(ws,id,signal))return false;const current=controller;if(current&&current.signal===signal)current.abort();clearProjectData();error.value=l('项目或来源授权已变化，受限内容已清除。','Project or source access changed. Restricted content was cleared.');return true}
async function refreshMaterials(){const ws=workspace.currentWorkspaceId||'',id=projectId.value,signal=controller?.signal;if(!ws||!id||!signal)return;materialsLoading.value=true;materialsError.value='';try{const view=await biddingApi.materials(ws,id,signal);if(assertCurrent(ws,id,signal))materials.value=view.items||[]}catch(cause){if(!signal.aborted&&assertCurrent(ws,id,signal)){materials.value=[];materialsError.value=accessDenied(cause)?l('授权材料当前不可用，内容已清除。','Authorized materials are unavailable; their content was cleared.'):l('授权材料读取失败。','Could not load authorized materials.')}}finally{if(!signal.aborted)materialsLoading.value=false}}
async function refreshOutline(){const ws=workspace.currentWorkspaceId||'',id=projectId.value,signal=controller?.signal;if(!ws||!id||!signal)return;outlineError.value='';try{const value=await biddingApi.outline(ws,id,signal);if(assertCurrent(ws,id,signal))outline.value={...value,candidates:value.candidates||[]}}catch(cause){if(!signal.aborted&&assertCurrent(ws,id,signal)){outline.value={candidates:[]};if(accessDenied(cause)){outlineSavedRef.value=undefined;outlineClearToken.value++;outlineSurface.value?.clearSensitiveDraft()}outlineError.value=accessDenied(cause)?l('目录内容当前不可访问，已清除。','Outline data is unavailable and was cleared.'):l('目录读取失败。','Could not load the outline.')}}}
async function refreshWriting(){const ws=workspace.currentWorkspaceId||'',id=projectId.value,signal=controller?.signal;if(!ws||!id||!signal)return;writingError.value='';try{const value=await biddingApi.writing(ws,id,signal);if(assertCurrent(ws,id,signal))writing.value={...value,chapters:value.chapters||[]}}catch(cause){if(!signal.aborted&&assertCurrent(ws,id,signal)){writing.value={chapters:[]};if(accessDenied(cause)){writingClearToken.value++;writingSurface.value?.clearSensitiveDraft()}writingError.value=accessDenied(cause)?l('正文当前不可访问，已清除。','Writing data is unavailable and was cleared.'):l('正文读取失败。','Could not load chapter writing.')}}}
async function refreshChangeImpact(){const ws=workspace.currentWorkspaceId||'',id=projectId.value,signal=controller?.signal;if(!ws||!id||!signal)return;changeImpactLoading.value=true;changeImpactError.value='';try{const value=await biddingApi.changeImpact(ws,id,signal);if(assertCurrent(ws,id,signal))changeImpact.value={...value,events:Array.isArray(value.events)?value.events:[],formalBlocked:value.formalBlocked!==false}}catch(cause){if(!signal.aborted&&assertCurrent(ws,id,signal)){if(accessDenied(cause))changeImpact.value={events:[],formalBlocked:true};changeImpactError.value=accessDenied(cause)?l('版本变更信息当前不可访问，已清除。','Change impact data is unavailable and was cleared.'):l('版本变更影响读取失败。','Could not refresh version impact.')}}finally{if(!signal.aborted)changeImpactLoading.value=false}}
async function confirmChangeImpact(payload:ChangeImpactConfirmationPayload){const current=project.value,ws=workspace.currentWorkspaceId||'',id=current?.id||'',signal=controller?.signal;if(!current||!canApproveProject.value||!payload)return;changeImpactLoading.value=true;changeImpactError.value='';try{await biddingApi.command(ws,id,{operationId:operationId(),expected:current.ref,action:'CONFIRM_CHANGE_IMPACT',payload});if(p2ScopeCurrent(ws,id,signal))await refreshAll()}catch(cause){if(clearDeniedP2Scope(cause,ws,id,signal))return;if(!p2ScopeCurrent(ws,id,signal))return;if(isConflict(cause)){await load();if(project.value)changeImpactError.value=l('版本已变化；影响信息已刷新，请核对后重试。','The project version changed. Impact data was refreshed; review it before retrying.')}else changeImpactError.value=l('无法确认版本变更影响。','Could not confirm version change impact.')}finally{if(p2ScopeCurrent(ws,id,signal))changeImpactLoading.value=false}}
async function refreshP2(){await Promise.all([refreshMaterials(),refreshOutline(),refreshWriting(),refreshChangeImpact()])}
async function refreshReviewAndArtifacts(){const ws=workspace.currentWorkspaceId||'',id=projectId.value,signal=controller?.signal;if(!ws||!id||!signal)return;reviewBusy.value=true;artifactLoading.value=true;try{const [review,templateRows,firstPage]=await Promise.all([biddingApi.review(ws,id,signal),biddingApi.templates(ws,id,signal),biddingApi.tasks(ws,id,signal)]);if(!assertCurrent(ws,id,signal))return;reviewView.value=review;templates.value=templateRows;const pages=[firstPage];for(let page=2;page<=Math.ceil(firstPage.total/firstPage.pageSize);page++)pages.push(await biddingApi.tasks(ws,id,signal,page,firstPage.pageSize));const exportTasks=pages.flatMap(page=>page.items).filter(task=>task.skillId==='bidding-document-export'&&task.status==='SUCCEEDED');const rows=await Promise.all(exportTasks.map(async task=>{const detail=await biddingApi.task(ws,task.taskId,signal);const root=detail as Record<string,unknown>,result=(root.effectiveResult||root.result||{}) as Record<string,unknown>,manifest=(result.payload||result) as Record<string,unknown>;const artifactId=typeof manifest.artifactId==='string'?manifest.artifactId:'';if(!artifactId)return undefined;try{return await biddingApi.artifact(ws,id,artifactId,signal)}catch(cause){if(responseStatus(cause)===404)return undefined;throw cause}}));if(assertCurrent(ws,id,signal))artifacts.value=rows.filter((item):item is ArtifactMetadata=>!!item).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))}catch(cause){if(!signal.aborted&&assertCurrent(ws,id,signal)){if(accessDenied(cause))handleReadFailure(cause);else error.value=l('审核与文件读取失败。','Could not load review and export data.')}}finally{if(!signal.aborted){reviewBusy.value=false;artifactLoading.value=false}}}
function reviewDecisionCommand(action:string,payload:Record<string,unknown>,expected:Ref){const activeProject=project.value,ws=workspace.currentWorkspaceId||'',id=activeProject?.id||'',signal=controller?.signal;if(!activeProject||!p2ScopeCurrent(ws,id,signal))return Promise.resolve(false);reviewBusy.value=true;return biddingApi.command(ws,id,{operationId:operationId(),expected,action,payload}).then(async()=>{if(p2ScopeCurrent(ws,id,signal)){decisionOpen.value=false;await load()}return true}).catch(cause=>{if(clearDeniedP2Scope(cause,ws,id,signal))return false;if(!p2ScopeCurrent(ws,id,signal))return false;if(isConflict(cause))void load();error.value=isConflict(cause)?l('版本已变化；输入已保留，请刷新后核对。','The version changed. Your input is retained; refresh and review before retrying.'):l('无法保存审核处置。','Could not save the review decision.');return false}).finally(()=>{if(p2ScopeCurrent(ws,id,signal))reviewBusy.value=false})}
async function dispatchReview(manuscriptRef:Ref){const current=project.value;if(!current||!capabilities.value?.canWrite)return;await reviewDecisionCommand('DISPATCH_REVIEW',{manuscriptRef},manuscriptRef)}
async function prepareExport(){const current=project.value,ws=workspace.currentWorkspaceId||'';if(!current||!capabilities.value?.canWrite)return;exportBusy.value=true;try{await biddingApi.command(ws,current.id,{operationId:operationId(),expected:current.ref,action:'PREPARE_EXPORT',payload:{}});await load()}catch(cause){if(handleReadFailure(cause))return;commandError(cause)}finally{exportBusy.value=false}}
async function generateExport(mode:'preview'|'candidate'){const current=project.value,manuscript=writing.value.manuscript,template=templates.value.find(item=>item.status==='PREPARED'),ws=workspace.currentWorkspaceId||'';if(!current||!capabilities.value?.canWrite||!manuscript||!template?.ref||!template.formatRef)return;exportBusy.value=true;try{await biddingApi.command(ws,current.id,{operationId:operationId(),expected:current.ref,action:'DISPATCH_EXPORT',payload:{manuscriptRef:manuscript.ref,templateRef:template.ref,formatRef:template.formatRef,mode}});await load()}catch(cause){if(handleReadFailure(cause))return;commandError(cause)}finally{exportBusy.value=false}}
async function openApproval(artifact:ArtifactMetadata){const ws=workspace.currentWorkspaceId||'',id=project.value?.id||'',signal=controller?.signal;if(!canApproveProject.value||!signal)return;approvalBusy.value=true;approvalConflict.value=false;try{const context=await biddingApi.approvalContext(ws,id,artifact.artifactId,signal);if(assertCurrent(ws,id,signal)){approvalContext.value=context;approvalOpen.value=true}}catch(cause){if(!signal.aborted&&assertCurrent(ws,id,signal)){if(accessDenied(cause))handleReadFailure(cause);else error.value=l('无法读取当前审定条件。','Could not load current approval requirements.')}}finally{if(!signal.aborted)approvalBusy.value=false}}
async function approveArtifact(payload:{artifactId:string;digest:string;manuscriptRef:Ref;templateRef:Ref;formatRef:Ref;reviewRef:Ref;inspection:{opened:true;layoutChecked:true;reason:string}}){const context=approvalContext.value,current=project.value,ws=workspace.currentWorkspaceId||'';if(!current||!context?.artifactRef||!canApproveProject.value)return;approvalBusy.value=true;try{await biddingApi.command(ws,current.id,{operationId:operationId(),expected:context.artifactRef,action:'APPROVE_ARTIFACT',payload});approvalOpen.value=false;approvalContext.value=undefined;approvalConflict.value=false;await load()}catch(cause){if(handleReadFailure(cause))return;if(isConflict(cause)){approvalConflict.value=true;approvalContext.value=undefined;await load();if(project.value?.id===current.id)try{const fresh=await biddingApi.approvalContext(ws,current.id,payload.artifactId,controller?.signal);if(project.value?.id===current.id){approvalContext.value=fresh;approvalOpen.value=true}}catch(refreshCause){if(handleReadFailure(refreshCause))return;error.value=l('审定条件已变化，请刷新后重新打开。','Approval state changed. Refresh and reopen the dialog.')}}else commandError(cause)}finally{approvalBusy.value=false}}
async function downloadArtifact(artifact:ArtifactMetadata,mode:'candidate'|'preview'|'formal'){const ws=workspace.currentWorkspaceId||'',id=project.value?.id||'',signal=controller?.signal;if(!ws||!id||!signal)return;try{const blob=await biddingApi.download(ws,id,artifact.artifactId,mode);if(!assertCurrent(ws,id,signal))return;const url=URL.createObjectURL(blob),anchor=document.createElement('a');downloadUrls.add(url);anchor.href=url;anchor.download='technical-proposal.docx';anchor.rel='noopener';document.body.append(anchor);anchor.click();anchor.remove();window.setTimeout(()=>{URL.revokeObjectURL(url);downloadUrls.delete(url)},0)}catch(cause){if(!signal.aborted&&assertCurrent(ws,id,signal)){if(accessDenied(cause))handleReadFailure(cause);else error.value=l('文件下载失败。','Could not download the file.')}}}
function openFindingDecision(item:BiddingReviewFinding,decision:'DISMISS_WITH_EVIDENCE'|'DEFER_SUGGESTION'){activeFinding.value=item;activeTodo.value=undefined;decisionAction.value=decision;decisionReason.value='';decisionEvidenceKey.value='';decisionBlockId.value='';decisionOpen.value=true}
function openTodoClassification(todo:BiddingHumanTodo){if(!canApproveProject.value)return;activeTodo.value=todo;activeFinding.value=undefined;decisionAction.value='CLASSIFY_HUMAN_TODO';decisionAffectsTechnical.value=true;decisionReason.value='';decisionEvidenceKey.value='';decisionBlockId.value='';decisionOpen.value=true}
function openTodoResolution(todo:BiddingHumanTodo){activeTodo.value=todo;activeFinding.value=undefined;decisionAction.value='RESOLVE_HUMAN_TODO';decisionReason.value='';decisionEvidenceKey.value='';decisionBlockId.value='';decisionOpen.value=true}
function evidencePayload(){const source=selectedEvidenceSource.value,block=source?.blocks?.find(item=>item.id===decisionBlockId.value);return source&&block?[{sourceRef:{kind:'source',id:source.sourceId,version:source.version,digest:source.digest},blockId:block.id,quote:block.text}]:[]}
async function submitReviewDecision(){const current=project.value;if(!current)return;const evidenceRefs=evidencePayload();if(decisionAction.value==='CLASSIFY_HUMAN_TODO'&&activeTodo.value){await reviewDecisionCommand('CLASSIFY_HUMAN_TODO',{todoRef:activeTodo.value.ref,affectsTechnical:decisionAffectsTechnical.value,reason:decisionReason.value.trim(),evidenceRefs},current.ref);return}if(decisionAction.value==='RESOLVE_HUMAN_TODO'&&activeTodo.value){await reviewDecisionCommand('RESOLVE_HUMAN_TODO',{todoRef:activeTodo.value.ref,reason:decisionReason.value.trim(),evidenceRefs},activeTodo.value.ref);return}if(activeFinding.value){await reviewDecisionCommand('RESOLVE_FINDING',{findingRef:activeFinding.value.findingRef,decision:decisionAction.value,reason:decisionReason.value.trim(),evidenceRefs},current.ref)}}
async function targetFinding(item:BiddingReviewFinding){const chapterRef=item.finding.chapterRefs?.map(ref=>writing.value.chapters.find(chapter=>chapter.chapterId===ref.id)?.editExpectedRef).find((ref):ref is Ref=>!!ref);if(!chapterRef||!project.value||!writing.value.manuscript){error.value=l('找不到当前章节版本，无法派发定向整改。','The current chapter revision is unavailable for targeted revision.');return}const result=await reviewDecisionCommand('RESOLVE_FINDING',{findingRef:item.findingRef,decision:'FIX',reason:item.finding.recommendation||item.finding.description||'Targeted revision',evidenceRefs:[]},project.value.ref);if(!result)return;const accepted=await executeP2('REVISE_CHAPTER',{manuscriptRef:writing.value.manuscript.ref,chapterRef,selectedFindingRefs:[item.findingRef]},chapterRef,'writing');if(accepted){tab.value='writing';writingSurface.value?.focusChapter(item.finding.chapterRefs?.[0]?.id||'')}}
function focusChapter(chapterId:string){tab.value='writing';writingSurface.value?.focusChapter(chapterId)}
function artifactDraftDirty(){return decisionOpen.value&&!!decisionReason.value.trim()||approvalOpen.value}
async function refreshAll(){await load()}
function commandError(cause:unknown){conflict.value=isConflict(cause);error.value=conflict.value?l('版本冲突：当前编辑内容已保留，请刷新核对后再提交。','Version conflict: your edits are retained. Refresh and compare before submitting.'):l('操作失败，请检查当前项目状态后重试。','Action failed. Check the current project state and retry.')}
async function assignEmployees(binding:Record<string,string|null>){if(!project.value||!canApproveProject.value)return;saving.value=true;error.value='';try{await biddingApi.command(workspace.currentWorkspaceId!,project.value.id,{operationId:operationId(),expected:project.value.ref,action:'ASSIGN_EMPLOYEES',payload:binding});await load()}catch(cause){commandError(cause)}finally{saving.value=false}}
async function saveProject(){if(!project.value||!canApproveProject.value)return;saving.value=true;try{await biddingApi.command(workspace.currentWorkspaceId!,project.value.id,{operationId:operationId(),expected:project.value.ref,action:'UPDATE_PROJECT',payload:{name:projectDraft.name.trim(),lotName:projectDraft.lotName.trim(),ownerId:projectDraft.ownerId}});ownerDialog.value=false;conflict.value=false;await load()}catch(cause){commandError(cause)}finally{saving.value=false}}
async function dispatchAnalysis(){if(!project.value||!sourceSet.value?.ref)return;dispatching.value=true;try{await biddingApi.command(workspace.currentWorkspaceId!,project.value.id,{operationId:operationId(),expected:project.value.ref,action:'DISPATCH_ANALYSIS',payload:{sourceSetRef:sourceSet.value.ref}});tab.value='analysis';taskDrawer.value=true;await refreshAll()}catch(cause){commandError(cause)}finally{dispatching.value=false}}
async function retrySource(source:Source){if(!project.value)return;try{await biddingApi.command(workspace.currentWorkspaceId!,project.value.id,{operationId:operationId(),expected:project.value.ref,action:'RETRY_SOURCE_READ',payload:{sourceRef:{kind:'source',id:source.sourceId,version:source.version,digest:source.digest}}});await refreshSources()}catch(cause){commandError(cause)}}
async function editAnalysis(body:{taskGroupId:string;skillId:string;payload:Record<string,unknown>;reason:string}){if(!project.value)return;try{await biddingApi.command(workspace.currentWorkspaceId!,project.value.id,{operationId:operationId(),expected:project.value.ref,action:'EDIT_ANALYSIS_ITEM',payload:body});await refreshAnalysis()}catch(cause){commandError(cause)}}
async function confirmAnalysis(groupId:string,autoPlanOutline=false){if(!project.value||!canApproveProject.value)return;try{await biddingApi.command(workspace.currentWorkspaceId!,project.value.id,{operationId:operationId(),expected:project.value.ref,action:'CONFIRM_ANALYSIS',payload:{taskGroupId:groupId,autoPlanOutline}});await refreshAll()}catch(cause){commandError(cause)}}
async function executeP2(action:string,payload:Record<string,unknown>,expected:Ref,area:'outline'|'writing'|'materials'='writing'):Promise<boolean> {const activeProject=project.value,ws=workspace.currentWorkspaceId||'',id=activeProject?.id||'',signal=controller?.signal;if(!activeProject||!capabilities.value?.canWrite||!p2ScopeCurrent(ws,id,signal))return false;const requestToken=++p2RequestToken;p2Busy.value=true;outlineError.value='';writingError.value='';materialsError.value='';error.value='';try{const result=await biddingApi.command(ws,id,{operationId:operationId(),expected,action,payload});if(!p2ScopeCurrent(ws,id,signal))return false;if(action==='EDIT_CHAPTER')writingSavedToken.value++;if(action==='SAVE_OUTLINE'&&result.ref)outlineSavedRef.value=result.ref;await refreshAll();return true}catch(cause){if(clearDeniedP2Scope(cause,ws,id,signal))return false;if(!p2ScopeCurrent(ws,id,signal))return false;conflict.value=isConflict(cause);const message=conflict.value?l('版本已变化，编辑草稿已保留。请读取最新版本后核对。','The version changed. Your draft is retained; reload and compare before retrying.'):l('操作失败，请检查当前版本和权限后重试。','The action failed. Check the current version and permissions, then retry.');error.value=message;if(area==='outline')outlineError.value=message;if(area==='writing')writingError.value=message;if(area==='materials')materialsError.value=message;return false}finally{if(requestToken===p2RequestToken)p2Busy.value=false}}
function outlineCommand(body:{action:string;payload:Record<string,unknown>;expected:Ref}){if(!project.value)return;const area=body.action==='BIND_MATERIAL'?'materials':'outline';if(body.action==='SAVE_OUTLINE')outlineSavedRef.value=undefined;if(body.action==='DISPATCH_OUTLINE')outlineDispatching.value=true;else if(body.action==='SAVE_OUTLINE')outlineSaving.value=true;else if(body.action==='CONFIRM_OUTLINE')outlineConfirming.value=true;void executeP2(body.action,body.payload,body.expected,area).finally(()=>{outlineDispatching.value=false;outlineSaving.value=false;outlineConfirming.value=false})}
async function receiveHandoff(payload:{presalesProjectId:string;releaseId:string;expectedDigest:string;receivedNotes:string[]}){if(!project.value)return;if(await executeP2('RECEIVE_HANDOFF',payload,project.value.ref,'materials'))handoffOpen.value=false}
async function bindMaterial(payload:{kind:'WIKI_PAGE';knowledgeBaseId:string;pageId:string;expectedDigest:string;applicability:string}){if(!project.value)return;await executeP2('BIND_MATERIAL',payload,project.value.ref,'materials')}
async function dispatchWriting(chapterIds:string[]){if(!project.value||!outline.value.confirmed)return;dispatchingChapterIds.value=[...new Set([...dispatchingChapterIds.value,...chapterIds])];try{await executeP2('DISPATCH_WRITING',{outlineRef:outline.value.confirmed.ref,chapterIds,materialRefs:materials.value.filter(item=>item.validity==='VALID').map(item=>item.ref)},project.value.ref,'writing')}finally{dispatchingChapterIds.value=dispatchingChapterIds.value.filter(id=>!chapterIds.includes(id))}}
function writingCommand(body:{action:string;payload:Record<string,unknown>;expected:Ref}){void executeP2(body.action,body.payload,body.expected,'writing')}
async function retryWritingTask(taskId:string){if(!project.value)return;await executeP2('RETRY_TASK',{taskId},project.value.ref,'writing')}
async function assembleManuscript(refs:{chapterId:string;ref:Ref}[]){if(!project.value||!outline.value.confirmed)return;await executeP2('ASSEMBLE_MANUSCRIPT',{outlineRef:outline.value.confirmed.ref,chapterRefs:refs},project.value.ref,'writing')}
function preview(source:Source){previewSource.value=source;previewOpen.value=true}
function openEvidence(value:Record<string,unknown>){evidenceRef.value=value;evidenceOpen.value=true}
function hasUnsavedWork(){return projectDraftChanged.value||!!outlineSurface.value?.isDirty()||!!writingSurface.value?.isDirty()||artifactDraftDirty()}
async function confirmLeave(){if(!hasUnsavedWork()&&!p2Busy.value&&!saving.value)return true;try{await ElMessageBox.confirm(l('放弃尚未保存的投标修改？','Discard unsaved bidding changes?'),l('未保存修改','Unsaved changes'),{confirmButtonText:l('离开','Leave'),cancelButtonText:l('留在此页','Stay'),type:'warning'});return true}catch{return false}}
async function beforeTabLeave(){return hasUnsavedWork()?confirmLeave():true}
function beforeUnload(event:BeforeUnloadEvent){if(hasUnsavedWork()||p2Busy.value||saving.value){event.preventDefault();event.returnValue=''}}
onBeforeRouteLeave(confirmLeave);onBeforeRouteUpdate(confirmLeave)
watch(()=>workspace.currentWorkspaceId,()=>{taskDrawer.value=false;previewOpen.value=false;clearReviewState();void load()})
watch(projectId,(value,previous)=>{if(value!==previous){handoffOpen.value=false;materials.value=[];outline.value={candidates:[]};writing.value={chapters:[]};changeImpact.value={events:[],formalBlocked:false};changeImpactError.value='';clearReviewState()}void load()})
watch(tab,value=>{if(value==='review')void refreshReviewAndArtifacts()})
onMounted(()=>{unregister=workspace.registerBeforeSwitch(async()=>{if(!await confirmLeave())return false;controller?.abort();return true});window.addEventListener('beforeunload',beforeUnload);void load()})
onBeforeUnmount(()=>{controller?.abort();unregister?.();window.removeEventListener('beforeunload',beforeUnload);for(const url of downloadUrls)URL.revokeObjectURL(url);downloadUrls.clear()})
</script>
<style scoped>
.bidding-workbench { padding:24px 32px 32px; min-width:0; color:var(--mc-text-primary); }.page-heading { display:flex; justify-content:space-between; align-items:center; gap:16px; margin-bottom:18px; }.page-heading>div:first-child { min-width:0; }.page-heading h1 { margin:4px 0 0; font-size:24px; font-weight:600; }.heading-actions { display:flex; gap:8px; align-items:center; flex-wrap:nowrap; }.heading-actions>.el-button{margin:0}.workbench-tabs { min-width:0; }.review-export-layout{display:grid;gap:28px;min-width:0}.el-button:focus-visible { outline:2px solid var(--mc-primary); outline-offset:2px; }@media(max-width:768px){.bidding-workbench{padding:16px}.page-heading{align-items:flex-start;flex-direction:column}.heading-actions{width:100%;flex-wrap:wrap;justify-content:flex-start}}
</style>
