package vip.mate.bidding;

import com.fasterxml.jackson.databind.JsonNode;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Test;

class BiddingApprovalTest extends BiddingHttpFixture {
    @Test void approvalCommandIsARealApproverGatedCommand() throws Exception {
        var project=api("POST","/projects","owner",workspace,Map.of("operationId",UUID.randomUUID().toString(),"name","审批门禁","lotName","一标段"),200);
        ObjectNode payload=json.createObjectNode().put("artifactId","missing").put("digest","forged");
        payload.putObject("inspection").put("opened",true).put("layoutChecked",true).put("reason","checked");
        ObjectNode command=json.createObjectNode().put("operationId",UUID.randomUUID().toString());
        command.set("expected",json.valueToTree(ref(project)));command.put("action","APPROVE_ARTIFACT").set("payload",payload);
        JsonNode denied=api("POST","/projects/"+project.path("id").asText()+"/commands","member",workspace,command,403);
        assertEquals("FORBIDDEN",denied.path("data").path("code").asText());
        JsonNode missing=api("POST","/projects/"+project.path("id").asText()+"/commands","owner",workspace,command,404);
        assertTrue(missing.toString().contains("ARTIFACT_NOT_FOUND"));
    }
}

@org.springframework.boot.test.context.SpringBootTest(classes=vip.mate.MateClawApplication.class,
        webEnvironment=org.springframework.boot.test.context.SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties={"spring.datasource.url=jdbc:h2:mem:bidding_approval_e2e;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000",
                "spring.ai.dashscope.api-key=test-key","mateclaw.semantic.enabled=false","mateclaw.presales.enabled=false",
                "mateclaw.bidding.enabled=true","mateclaw.bidding.scheduler-enabled=false"})
@org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
class BiddingApprovalEndToEndTest {
    private static final java.util.concurrent.atomic.AtomicLong IDS=new java.util.concurrent.atomic.AtomicLong(9_800_000L);
    @org.junit.jupiter.api.io.TempDir java.nio.file.Path temp;
    @org.springframework.beans.factory.annotation.Autowired org.springframework.test.web.servlet.MockMvc mvc;
    @org.springframework.beans.factory.annotation.Autowired com.fasterxml.jackson.databind.ObjectMapper json;
    @org.springframework.beans.factory.annotation.Autowired org.springframework.jdbc.core.JdbcTemplate jdbc;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.auth.service.AuthService auth;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.workspace.core.service.WorkspaceService workspaces;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.agent.AgentService agents;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.agent.binding.service.AgentBindingService agentBindings;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.skill.runtime.SkillRuntimeService skills;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.llm.service.ModelConfigService modelConfigs;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.llm.service.ModelProviderService modelProviders;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingEmployeeBindings employees;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingSourceService sources;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingWritingService writing;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingReviewService reviews;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingTaskService tasks;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingArtifactService artifacts;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingExportTool exportTool;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingRepository repository;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingProjectService projects;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingOutlineService outlines;
    @org.springframework.beans.factory.annotation.Autowired vip.mate.bidding.BiddingApprovalService approvals;
    @org.springframework.boot.test.mock.mockito.SpyBean vip.mate.bidding.BiddingDocxRenderer renderer;
    private String workspace,token;

    @org.junit.jupiter.api.Test void completeReviewApprovalAndFormalDownloadPreserveExactCandidateBytes() throws Exception {
        var user=new vip.mate.auth.model.UserEntity();user.setUsername("approval_"+java.util.UUID.randomUUID());user.setPassword("pw");user.setRole("user");user.setDeleted(0);auth.createUser(user);
        var login=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/v1/auth/login").contentType("application/json").content(json.writeValueAsString(java.util.Map.of("username",user.getUsername(),"password","pw")))).andReturn().getResponse();
        org.junit.jupiter.api.Assertions.assertEquals(200,login.getStatus(),login.getContentAsString());token="Bearer "+json.readTree(login.getContentAsString()).path("data").path("token").asText();
        var ws=new vip.mate.workspace.core.model.WorkspaceEntity();ws.setName("approval-"+java.util.UUID.randomUUID());ws.setDeleted(0);workspace=workspaces.create(ws,user.getId()).getId().toString();
        jdbc.update("UPDATE mate_model_provider SET api_key='test-key',enabled=TRUE WHERE provider_id='dashscope'");
        var defaultModel=modelConfigs.getDefaultModel();long modelId=IDS.incrementAndGet();String modelName="approval-model-"+modelId;
        jdbc.update("INSERT INTO mate_model_config(id,name,provider,model_name,model_type,enabled,is_default,create_time,update_time,deleted) VALUES(?,?,?,?,'chat',TRUE,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0)",modelId,"approval test model",defaultModel.getProvider(),modelName);
        java.util.Map<String,Long> skillIds=new java.util.LinkedHashMap<>();java.util.Map<String,java.nio.file.Path> dirs=new java.util.LinkedHashMap<>();
        java.util.List<String> names=java.util.List.of("bidding-tender-profile","bidding-elimination-analysis","bidding-requirement-analysis","bidding-scoring-analysis","bidding-outline-planning","bidding-technical-writing","bidding-technical-review","bidding-document-export");
        for(String name:names)skillIds.put(name,seedSkill(name,dirs));skills.refreshActiveSkills();
        var analyst=createAgent("analyst",modelName);var writer=createAgent("writer",modelName);var reviewer=createAgent("reviewer",modelName);
        agentBindings.setSkillBindings(analyst.getId(),names.subList(0,4).stream().map(skillIds::get).toList());
        agentBindings.setSkillBindings(writer.getId(),java.util.List.of(skillIds.get("bidding-outline-planning"),skillIds.get("bidding-technical-writing"),skillIds.get("bidding-document-export")));
        agentBindings.setSkillBindings(reviewer.getId(),java.util.List.of(skillIds.get("bidding-technical-review")));
        com.fasterxml.jackson.databind.JsonNode project=http("POST","/api/v1/bidding/projects",java.util.Map.of("operationId",java.util.UUID.randomUUID().toString(),"name","审批闭环","lotName","一标段"),200);
        String projectId=project.path("data").path("id").asText();var scope=new BiddingTypes.Scope(workspace,user.getId().toString(),projectId);
        ObjectNode assign=json.createObjectNode().put("operationId","bind-review-export-"+projectId);assign.set("expected",project.path("data").path("ref").deepCopy());assign.put("action","ASSIGN_EMPLOYEES");var binding=assign.putObject("payload");binding.put("analystAgentId",analyst.getId().toString()).put("writerAgentId",writer.getId().toString()).put("reviewerAgentId",reviewer.getId().toString());
        com.fasterxml.jackson.databind.JsonNode assigned=http("POST","/api/v1/bidding/projects/"+projectId+"/commands",assign,200);var projectRef=json.treeToValue(assigned.path("data").path("result").path("ref"),BiddingTypes.Ref.class);
        var uploaded=sources.upload(scope,"source-"+projectId,"TENDER",null,docx("接口响应时间不超过2秒"),"招标文件.docx");org.junit.jupiter.api.Assertions.assertEquals(1,sources.readPending(2));BiddingTypes.Ref source=json.treeToValue(uploaded.path("ref"),BiddingTypes.Ref.class);var sourceRow=repository.source(scope.workspaceId(),scope.projectId(),source.id(),source.version());String blockId=json.readTree(sourceRow.blocks()).get(0).path("id").asText();
        ObjectNode sourceSetPayload=json.createObjectNode().putNull("expectedSourceSetRef");sourceSetPayload.set("sourceRefs",json.valueToTree(java.util.List.of(source)));sourceSetPayload.putArray("exclusions");var sourceSet=sources.confirmSet(scope,new BiddingTypes.Command("confirm-source-"+projectId,projectRef,"CONFIRM_SOURCE_SET",sourceSetPayload));BiddingTypes.Ref sourceSetRef=json.treeToValue(sourceSet.path("ref"),BiddingTypes.Ref.class);
        ObjectNode baseline=json.createObjectNode().put("schemaVersion","1");baseline.set("sourceSetRef",json.valueToTree(sourceSetRef));var analyses=baseline.putObject("analyses");analyses.putObject("bidding-tender-profile").putArray("formatRequirements");var requirements=analyses.putObject("bidding-requirement-analysis").putArray("requirements");var req=requirements.addObject().put("id","REQ-1").put("category","TECHNICAL").put("text","接口响应时间不超过2秒");req.putArray("constraints").add("接口响应时间不超过2秒");req.putArray("evidenceRefs").addObject().put("sourceId",source.id()).put("version",source.version()).put("blockId",blockId).put("quote","接口响应时间不超过2秒");req.putArray("unknowns");var commercial=requirements.addObject().put("id","COM-1").put("category","COMMERCIAL").put("text","报价口径由商务负责人确认");commercial.putArray("constraints");commercial.putArray("evidenceRefs").addObject().put("sourceId",source.id()).put("version",source.version()).put("blockId",blockId).put("quote","接口响应时间不超过2秒");commercial.putArray("unknowns");analyses.putObject("bidding-scoring-analysis").putArray("criteria");analyses.putObject("bidding-elimination-analysis").putArray("items");BiddingTypes.Ref baselineRef=save(scope,new BiddingTypes.Ref("analysisBaseline","current",1,digest(baseline)),baseline,java.util.List.of(sourceSetRef),"CONFIRMED",true);
        var emptyOutline=outlines.read(scope);BiddingTypes.Ref outlineGuard=json.treeToValue(emptyOutline.path("editExpectedRef"),BiddingTypes.Ref.class);ObjectNode outlineBody=json.createObjectNode().put("schemaVersion","1");var chapter=outlineBody.putArray("chapters").addObject().put("id","c1").put("order",1).put("title","技术方案").put("instructions","响应接口性能要求并说明验证方式");chapter.putNull("parentId");chapter.putArray("requirementRefs").add("REQ-1");chapter.putArray("scoringRefs");chapter.putArray("materialRefs");chapter.putArray("mandatoryOutlineRefs");outlineBody.putArray("unmappedItems");outlineBody.putArray("warnings");ObjectNode outlineSavePayload=json.createObjectNode();outlineSavePayload.set("payload",outlineBody);var outlineCandidate=outlines.save(scope,new BiddingTypes.Command("save-outline-"+projectId,outlineGuard,"SAVE_OUTLINE",outlineSavePayload));BiddingTypes.Ref candidateOutline=json.treeToValue(outlineCandidate.path("ref"),BiddingTypes.Ref.class);ObjectNode confirmOutline=json.createObjectNode();confirmOutline.set("outlineRef",json.valueToTree(candidateOutline));confirmOutline.put("reason","确认本标段目录");BiddingTypes.Ref confirmedOutline=json.treeToValue(outlines.confirm(scope,new BiddingTypes.Command("confirm-outline-"+projectId,candidateOutline,"CONFIRM_OUTLINE",confirmOutline)).path("ref"),BiddingTypes.Ref.class);
        var chapterState=writing.read(scope).path("chapters").get(0);BiddingTypes.Ref chapterGuard=json.treeToValue(chapterState.path("editExpectedRef"),BiddingTypes.Ref.class);ObjectNode edit=json.createObjectNode().put("chapterId","c1");edit.putArray("blocks").addObject().put("type","paragraph").put("text","本方案承诺接口响应时间不超过2秒，并提供压测记录。");edit.putArray("responses").addObject().put("requirementRef","REQ-1").put("status","RESPONDED").put("text","满足要求");edit.putArray("citations").addObject().put("requirementRef","REQ-1").put("sourceId",source.id()).put("version",source.version()).put("blockId",blockId).put("quote","接口响应时间不超过2秒");edit.putArray("missingMaterials");edit.putArray("unresolvedItems");BiddingTypes.Ref selectedChapter=json.treeToValue(writing.edit(scope,new BiddingTypes.Command("edit-chapter-"+projectId,chapterGuard,"EDIT_CHAPTER",edit)).path("ref"),BiddingTypes.Ref.class);
        ObjectNode assembly=json.createObjectNode().set("outlineRef",json.valueToTree(confirmedOutline));assembly.putArray("chapterRefs").addObject().put("chapterId","c1").set("ref",json.valueToTree(selectedChapter));BiddingTypes.Ref manuscript=json.treeToValue(writing.assemble(scope,new BiddingTypes.Command("assemble-"+projectId,confirmedOutline,"ASSEMBLE_MANUSCRIPT",assembly)).path("ref"),BiddingTypes.Ref.class);
        org.junit.jupiter.api.Assertions.assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM mate_bidding_task WHERE project_id=? AND status='QUEUED'",Integer.class,projectId));
        completeReviewTasks(scope,manuscript,2);
        org.junit.jupiter.api.Assertions.assertEquals("REVIEWED",reviews.read(scope).path("status").asText());BiddingTypes.Ref todoRef=json.treeToValue(reviews.read(scope).path("humanTodos").get(0).path("ref"),BiddingTypes.Ref.class);todoRef=classifyTodo(scope,todoRef,source,blockId,false);ObjectNode reviewEvidence=reviews.approvalEvidence(scope,manuscript);BiddingTypes.Ref reviewRef=json.treeToValue(reviewEvidence.path("reviewRef"),BiddingTypes.Ref.class);
        ObjectNode prep=artifacts.prepareExport(scope,new BiddingTypes.Command("prepare-"+projectId,projectRef,"PREPARE_EXPORT",json.createObjectNode()));BiddingTypes.Ref template=json.treeToValue(prep.path("templateRef"),BiddingTypes.Ref.class),format=json.treeToValue(prep.path("formatRef"),BiddingTypes.Ref.class);
        ObjectNode dispatch=json.createObjectNode().set("manuscriptRef",json.valueToTree(manuscript));dispatch.set("templateRef",json.valueToTree(template));dispatch.set("formatRef",json.valueToTree(format));dispatch.put("mode","candidate");artifacts.dispatch(scope,new BiddingTypes.Command("export-"+projectId,projectRef,"DISPATCH_EXPORT",dispatch));BiddingTypes.Claim claim=tasks.claimDue(java.time.Instant.now(),"approval-test",1).getFirst();
        var options=new vip.mate.agent.execution.ProjectExecutionOptions(claim.attemptId(),claim.modelConfigId(),claim.configDigest(),"bidding-document-export",claim.skill().digest(),claim.skill().files(),java.util.Set.of("bidding_export_document"),new BiddingToolScope(claim),0,false,false,12);var context=new org.springframework.ai.chat.model.ToolContext(java.util.Map.of(vip.mate.agent.execution.ProjectExecutionOptions.TOOL_CONTEXT_KEY,options));ObjectNode manifest=(ObjectNode)json.readTree(exportTool.generate(json.writeValueAsString(manuscript),json.writeValueAsString(template),json.writeValueAsString(format),context));tasks.complete(claim,new BiddingTypes.Execution(manifest,null,claim.skill().digest(),claim.configDigest(),null));
        String artifactId=manifest.path("artifactId").asText();byte[] dbBytes=jdbc.queryForObject("SELECT content FROM mate_bidding_artifact WHERE workspace_id=? AND project_id=? AND id=?",(rs,n)->rs.getBytes(1),workspace,projectId,artifactId);org.junit.jupiter.api.Assertions.assertArrayEquals(dbBytes,artifacts.download(scope,artifactId,"candidate"));org.junit.jupiter.api.Assertions.assertArrayEquals(dbBytes,content(projectId,artifactId,"candidate"));
        ObjectNode approval=json.createObjectNode().put("artifactId",artifactId).put("digest",manifest.path("digest").asText());approval.set("manuscriptRef",json.valueToTree(manuscript));approval.set("templateRef",json.valueToTree(template));approval.set("formatRef",json.valueToTree(format));approval.set("reviewRef",json.valueToTree(reviewRef));approval.putObject("inspection").put("opened",true).put("layoutChecked",true).put("reason","已逐页核对页眉、分页与技术响应");
        ObjectNode approveCommand=json.createObjectNode().put("operationId","approve-"+projectId);approveCommand.set("expected",json.valueToTree(new BiddingTypes.Ref("artifact",artifactId,1,manifest.path("digest").asText())));approveCommand.put("action","APPROVE_ARTIFACT");approveCommand.set("payload",approval);var approved=http("POST","/api/v1/bidding/projects/"+projectId+"/commands",approveCommand,200);org.junit.jupiter.api.Assertions.assertEquals("APPROVED",approved.path("data").path("status").asText());
        org.mockito.Mockito.clearInvocations(renderer);byte[] first=content(projectId,artifactId,"formal"),second=content(projectId,artifactId,"formal");org.junit.jupiter.api.Assertions.assertArrayEquals(dbBytes,first);org.junit.jupiter.api.Assertions.assertArrayEquals(dbBytes,second);org.mockito.Mockito.verifyNoInteractions(renderer);
        org.junit.jupiter.api.Assertions.assertEquals("no-store",mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/bidding/projects/"+projectId+"/artifacts/"+artifactId+"/content?mode=formal").header("Authorization",token).header("X-Workspace-Id",workspace)).andReturn().getResponse().getHeader("Cache-Control"));
        todoRef=classifyTodo(scope,todoRef,source,blockId,true);var technicalBlock=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/bidding/projects/"+projectId+"/artifacts/"+artifactId+"/content?mode=formal").header("Authorization",token).header("X-Workspace-Id",workspace)).andReturn().getResponse();org.junit.jupiter.api.Assertions.assertEquals(409,technicalBlock.getStatus());org.junit.jupiter.api.Assertions.assertEquals("HUMAN_TODO_BLOCKS_TECHNICAL_APPROVAL",json.readTree(technicalBlock.getContentAsString()).path("data").path("code").asText());todoRef=classifyTodo(scope,todoRef,source,blockId,false);var revertedBlock=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/bidding/projects/"+projectId+"/artifacts/"+artifactId+"/content?mode=formal").header("Authorization",token).header("X-Workspace-Id",workspace)).andReturn().getResponse();org.junit.jupiter.api.Assertions.assertEquals(409,revertedBlock.getStatus(),revertedBlock.getContentAsString());
        var nextGuard=json.treeToValue(outlines.read(scope).path("editExpectedRef"),BiddingTypes.Ref.class);ObjectNode replacementOutlineSave=json.createObjectNode().put("operationId","replace-outline-after-approval-"+projectId);replacementOutlineSave.set("expected",json.valueToTree(nextGuard));replacementOutlineSave.put("action","SAVE_OUTLINE");ObjectNode replacementOutlinePayload=json.createObjectNode().set("payload",outlineBody.deepCopy());replacementOutlineSave.set("payload",replacementOutlinePayload);var savedOutline=http("POST","/api/v1/bidding/projects/"+projectId+"/commands",replacementOutlineSave,200);BiddingTypes.Ref replacementOutline=json.treeToValue(savedOutline.path("data").path("ref"),BiddingTypes.Ref.class);ObjectNode replacementConfirm=json.createObjectNode().put("operationId","confirm-outline-after-approval-"+projectId);replacementConfirm.set("expected",json.valueToTree(replacementOutline));replacementConfirm.put("action","CONFIRM_OUTLINE");ObjectNode confirmPayload=json.createObjectNode().set("outlineRef",json.valueToTree(replacementOutline));confirmPayload.put("reason","目录变更使既有审批失效");replacementConfirm.set("payload",confirmPayload);http("POST","/api/v1/bidding/projects/"+projectId+"/commands",replacementConfirm,200);var staleFormal=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/bidding/projects/"+projectId+"/artifacts/"+artifactId+"/content?mode=formal").header("Authorization",token).header("X-Workspace-Id",workspace)).andReturn().getResponse();org.junit.jupiter.api.Assertions.assertEquals(422,staleFormal.getStatus(),staleFormal.getContentAsString());org.junit.jupiter.api.Assertions.assertEquals("DEPENDENCY_NOT_CONFIRMED",json.readTree(staleFormal.getContentAsString()).path("data").path("code").asText());org.junit.jupiter.api.Assertions.assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mate_bidding_decision WHERE workspace_id=? AND project_id=? AND id=? AND decision='APPROVE_ARTIFACT'",Integer.class,workspace,projectId,approved.path("data").path("decisionRef").path("id").asText()),"approval decision remains immutable history when its dependency closure changes");
    }

    private long seedSkill(String name,java.util.Map<String,java.nio.file.Path> dirs)throws Exception {long id=IDS.incrementAndGet();java.nio.file.Path source=java.nio.file.Path.of(getClass().getResource("/skills/"+name+"/SKILL.md").toURI()).getParent(),dest=java.nio.file.Files.createDirectory(temp.resolve("skill-"+id));try(var walk=java.nio.file.Files.walk(source)){for(var path:walk.toList())if(java.nio.file.Files.isRegularFile(path)){var target=dest.resolve(source.relativize(path).toString());java.nio.file.Files.createDirectories(target.getParent());java.nio.file.Files.copy(path,target);}}jdbc.update("INSERT INTO mate_skill(id,name,skill_type,version,skill_content,config_json,enabled,builtin,workspace_id,create_time,update_time,deleted) VALUES(?,?,'custom','1.0.0',?,?,TRUE,FALSE,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0)",id,name,java.nio.file.Files.readString(dest.resolve("SKILL.md")),json.writeValueAsString(java.util.Map.of("skillDir",dest.toString())),Long.valueOf(workspace));dirs.put(name,dest);return id;}
    private vip.mate.agent.model.AgentEntity createAgent(String role,String model)throws Exception {var agent=new vip.mate.agent.model.AgentEntity();agent.setName("approval-"+role+"-"+IDS.incrementAndGet());agent.setDescription("approval integration");agent.setAgentType("react");agent.setRuntimeType("native");agent.setSystemPrompt("Return structured task output");agent.setMaxIterations(12);agent.setWorkspaceId(Long.valueOf(workspace));agent.setModelName(model);return agents.createAgent(agent);}
    private com.fasterxml.jackson.databind.JsonNode http(String method,String path,Object body,int status)throws Exception {var response=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.request(org.springframework.http.HttpMethod.valueOf(method),path).header("Authorization",token).header("X-Workspace-Id",workspace).contentType("application/json").content(json.writeValueAsString(body))).andReturn().getResponse();org.junit.jupiter.api.Assertions.assertEquals(status,response.getStatus(),response.getContentAsString());return json.readTree(response.getContentAsString());}
    private byte[] content(String project,String artifact,String mode)throws Exception {var response=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/bidding/projects/"+project+"/artifacts/"+artifact+"/content?mode="+mode).header("Authorization",token).header("X-Workspace-Id",workspace)).andReturn().getResponse();org.junit.jupiter.api.Assertions.assertEquals(200,response.getStatus(),response.getContentAsString());org.junit.jupiter.api.Assertions.assertTrue(response.getHeader("Content-Disposition").contains("technical-proposal.docx"));return response.getContentAsByteArray();}
    private BiddingTypes.Ref classifyTodo(BiddingTypes.Scope scope,BiddingTypes.Ref todo,BiddingTypes.Ref source,String blockId,boolean affectsTechnical)throws Exception {ObjectNode command=json.createObjectNode().put("operationId","classify-"+todo.version()+"-"+affectsTechnical+"-"+UUID.randomUUID());command.set("expected",json.valueToTree(todo));command.put("action","CLASSIFY_HUMAN_TODO");ObjectNode payload=json.createObjectNode().set("todoRef",json.valueToTree(todo));payload.put("affectsTechnical",affectsTechnical).put("reason",affectsTechnical?"事实影响技术响应":"经核实仅属商务事项");payload.putArray("evidenceRefs").addObject().put("sourceId",source.id()).put("version",source.version()).put("blockId",blockId).put("quote","接口响应时间不超过2秒");command.set("payload",payload);var response=http("POST","/api/v1/bidding/projects/"+scope.projectId()+"/commands",command,200);return json.treeToValue(response.path("data").path("ref"),BiddingTypes.Ref.class);}
    private void completeReviewTasks(BiddingTypes.Scope scope,BiddingTypes.Ref manuscript,int count)throws Exception {for(int i=0;i<count;i++){var claim=tasks.claimDue(java.time.Instant.now(),"approval-review-"+i,1).getFirst();ObjectNode output=json.createObjectNode().put("schemaVersion","1");output.putArray("findings");ObjectNode coverage=output.putObject("coverage");var chapters=coverage.putArray("chapterRefs");var requirements=coverage.putArray("requirementRefs");for(var chapter:claim.input().path("chapters"))chapters.add(chapter.path("chapterRef").deepCopy());for(var req:claim.input().path("requirements"))requirements.add(req.path("id").asText());coverage.put("crossChapterReviewed",claim.input().path("_biddingTargetId").asText().endsWith(":cross"));output.putArray("limitations");output.putArray("warnings");tasks.complete(claim,new BiddingTypes.Execution(output,null,claim.skill().digest(),claim.configDigest(),null));}}
    private BiddingTypes.Ref save(BiddingTypes.Scope scope,BiddingTypes.Ref ref,ObjectNode body,java.util.List<BiddingTypes.Ref> refs,String status,boolean head)throws Exception {jdbc.update("INSERT INTO mate_bidding_revision(id,workspace_id,project_id,kind,object_id,version,payload_json,input_refs_json,status,digest,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)",java.util.UUID.randomUUID().toString(),workspace,scope.projectId(),ref.kind(),ref.id(),ref.version(),json.writeValueAsString(body),json.writeValueAsString(refs),status,ref.digest());if(head)jdbc.update("MERGE INTO mate_bidding_head(workspace_id,project_id,kind,object_id,version,selected_ref_json) KEY(workspace_id,project_id,kind,object_id) VALUES(?,?,?,?,?,?)",workspace,scope.projectId(),ref.kind(),ref.id(),ref.version(),json.writeValueAsString(ref));return ref;}
    private String digest(Object value)throws Exception{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(json.writeValueAsBytes(value)));}
    private byte[] docx(String text)throws Exception{try(var doc=new org.apache.poi.xwpf.usermodel.XWPFDocument();var out=new java.io.ByteArrayOutputStream()){doc.createParagraph().createRun().setText(text);doc.write(out);return out.toByteArray();}}
}
