INSERT INTO mate_wiki_knowledge_base(id,workspace_id,name) VALUES(42,7,'retained-kb');
INSERT INTO mate_wiki_raw_material(id,kb_id,title,original_content) VALUES(4201,42,'retained-source','do not delete');
INSERT INTO mate_wiki_page(id,kb_id,title,content) VALUES(4202,42,'retained-page','do not delete');
INSERT INTO mate_semantic_ontology(id,workspace_id,name,description,latest_version,latest_revision_id,draft_id,draft_counter,updated_at) VALUES('ont-old',7,'old test ontology','reset target',1,'rev-old',NULL,1,CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_ontology_revision(id,ontology_id,version,draft_version,revision_state,draft_slot,name,description,definition_json,base_revision_id,available_for_new_bindings,published_at,published_by,publication_note,document_text,document_syntax,document_digest,ontology_iri,version_iri,import_lock_digest,model_schema,imports_json,policy_json) VALUES('rev-old','ont-old',1,1,'PUBLISHED',NULL,'old test ontology','reset target',NULL,NULL,TRUE,CURRENT_TIMESTAMP,'seed','', 'Ontology(<urn:test:old>)','FUNCTIONAL','old-digest','urn:test:old',NULL,'imports','owl-document-v1','[{"artifactId":"artifact-old"}]','{"version":"old","rules":[]}');
INSERT INTO mate_semantic_graph(id,workspace_id,kb_id,ontology_revision_id,enabled,mutation_version,created_at,updated_at) VALUES('graph-old',7,42,'rev-old',TRUE,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_entity(id,graph_id,type_key,iri,asserted_types_json) VALUES('entity-old','graph-old',NULL,'urn:test:old:entity','["urn:test:Old"]');
INSERT INTO mate_semantic_ontology_axiom(revision_id,axiom_id,axiom_kind,axiom_text,signature_json) VALUES('rev-old','axiom-old','Declaration','Declaration(Class(<urn:test:Old>))','[]');
INSERT INTO mate_semantic_ontology_source_snapshot(id,workspace_id,kb_id,source_ref,source_title,source_text,source_digest,captured_by,captured_at) VALUES('osnap-old',7,42,'old-source','old source','old text','digest-old','seed',CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_ontology_source_snapshot(id,workspace_id,kb_id,source_ref,source_title,source_text,source_digest,captured_by,captured_at) VALUES('osnap-observed',7,42,'old-source','old source changed','changed text','digest-new','seed',CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_axiom_source(id,revision_id,axiom_id,source_snapshot_id,source_digest,exact_quote,start_code_point,end_code_point,origin,review_state,created_by,created_at) VALUES('binding-old','rev-old','axiom-old','osnap-old','digest-old','old text',0,8,'EXPERT','PENDING','seed',CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_ontology_source_review(id,binding_id,observed_digest,source_state,review_state,decision,reason,observed_snapshot_id) VALUES('review-old','binding-old','digest-new','CHANGED','PENDING',NULL,NULL,'osnap-observed');
INSERT INTO mate_semantic_source_snapshot(id,graph_id,text_content) VALUES('snap-old','graph-old','graph source');
INSERT INTO mate_semantic_import_job(id,graph_id,snapshot_id) VALUES('import-old','graph-old','snap-old');
INSERT INTO mate_semantic_evidence(id,graph_id,snapshot_id) VALUES('evidence-old','graph-old','snap-old');
INSERT INTO mate_semantic_statement(id,graph_id,current_revision) VALUES('statement-old','graph-old',1);
INSERT INTO mate_semantic_statement_revision(statement_id,revision,graph_id,ontology_revision_id,subject_id,content_json) VALUES('statement-old',1,'graph-old','rev-old','entity-old','{"assertion":"old"}');
INSERT INTO mate_semantic_revision_evidence(statement_id,revision,evidence_id) VALUES('statement-old',1,'evidence-old');
INSERT INTO mate_semantic_change_proposal(id,graph_id,target_statement_id,payload_json) VALUES('proposal-old','graph-old','statement-old','{"statementId":"statement-old"}');
INSERT INTO mate_semantic_conflict(id,graph_id,left_statement_id,right_statement_id) VALUES('conflict-old','graph-old','statement-old','statement-old');
INSERT INTO mate_semantic_source_governance(graph_id,source_id,state) VALUES('graph-old','source-old','WITHDRAWN');
INSERT INTO mate_semantic_snapshot_exclusion(graph_id,snapshot_id) VALUES('graph-old','snap-old');
INSERT INTO mate_semantic_mutation_command(id,graph_id,result_json) VALUES('mutation-old','graph-old','{"revisionId":"rev-old"}');
INSERT INTO mate_semantic_governance_event(id,workspace_id,graph_id,resource_id,result_json) VALUES('event-old',7,'graph-old','rev-old','{"ontologyId":"ont-old"}');
INSERT INTO mate_semantic_command_record(id,workspace_id,resource_id,result_json) VALUES('command-old',7,'rev-old','{"graphId":"graph-old"}');
INSERT INTO mate_semantic_governance_record(id,workspace_id,ontology_id,revision_id,detail_json) VALUES('gov-old',7,'ont-old','rev-old','{"graphId":"graph-old"}');
INSERT INTO mate_semantic_import_artifact(id,workspace_id,document_digest,document_syntax,document_text) VALUES('artifact-old',7,'artifact-digest','FUNCTIONAL','import artifact');
INSERT INTO mate_semantic_extraction_gate(id) VALUES(1);
INSERT INTO mate_semantic_extraction_task(id,workspace_id,graph_id,generation) VALUES('task-old','7','graph-old',3);
INSERT INTO mate_semantic_extraction_attempt(id,task_id) VALUES('attempt-old','task-old');
INSERT INTO mate_semantic_extraction_suggestion(id,task_id,attempt_id) VALUES('suggestion-old','task-old','attempt-old');
INSERT INTO mate_semantic_extraction_edit(suggestion_id,version,payload_json) VALUES('suggestion-old',1,'{}');
INSERT INTO mate_semantic_extraction_receipt(suggestion_id,edit_version,graph_id) VALUES('suggestion-old',1,'graph-old');
INSERT INTO mate_semantic_extraction_submission_intent(suggestion_id,edit_version,graph_id) VALUES('suggestion-old',1,'graph-old');
INSERT INTO mate_semantic_extraction_action(graph_id,operation_id,resource_id) VALUES('graph-old','action-old','suggestion-old');
INSERT INTO mate_semantic_ontology(id,workspace_id,name,description,latest_version,latest_revision_id,draft_id,draft_counter,updated_at) VALUES('ont-other',7,'other ontology','retained',1,'rev-other',NULL,1,CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_ontology_revision(id,ontology_id,version,draft_version,revision_state,draft_slot,name,description,definition_json,available_for_new_bindings,published_at,published_by,publication_note,document_text,document_syntax,document_digest,ontology_iri,import_lock_digest,model_schema,imports_json,policy_json) VALUES('rev-other','ont-other',1,1,'PUBLISHED',NULL,'other ontology','retained',NULL,TRUE,CURRENT_TIMESTAMP,'seed','', 'Ontology(<urn:test:other>)','FUNCTIONAL','other-digest','urn:test:other','imports','owl-document-v1','[]','{"version":"other","rules":[]}');
INSERT INTO mate_semantic_graph(id,workspace_id,kb_id,ontology_revision_id,enabled,mutation_version,created_at,updated_at) VALUES('graph-other',7,43,'rev-other',TRUE,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_source_change_run(id,graph_id,operation_id,status,expected_graph_version,request_digest,baseline_json,created_by,created_at,updated_at) VALUES('change-run-old','graph-old','source-change-old','OPEN',4,'request-digest','{}','seed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_source_change_lock(graph_id,source_kind,source_ref,touched_at) VALUES('graph-old','WIKI','source-old',CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_source_change(id,run_id,graph_id,source_kind,source_ref,old_snapshot_id,new_snapshot_id,old_digest,new_digest,source_state,observed_graph_version,created_by,created_at) VALUES('change-old','change-run-old','graph-old','WIKI','source-old','osnap-old','osnap-observed','digest-old','digest-new','CHANGED',4,'seed',CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_source_change_item(id,change_id,graph_id,source_kind,source_ref,item_kind,item_id,item_revision,old_snapshot_id,new_snapshot_id,old_digest,new_digest,source_state,review_state,decision,reason,decision_operation_id,observed_graph_version,created_by,created_at) VALUES('change-item-old','change-old','graph-old','WIKI','source-old','ASSERTION','statement-old',1,'osnap-old','osnap-observed','digest-old','digest-new','CHANGED','PENDING',NULL,NULL,NULL,4,'seed',CURRENT_TIMESTAMP);
INSERT INTO mate_semantic_command_record(id,workspace_id,resource_id,result_json) VALUES('command-decoy',7,'rev-old','{"graphId":"graph-other"}');
