import { createApp, h, nextTick, reactive } from 'vue'
import { createPinia, setActivePinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import ElementPlus from 'element-plus'
import { describe, expect, it, beforeEach, vi } from 'vitest'
import zh from '@/i18n/locales/zh-CN'
import { useWorkspaceStore } from '@/stores/useWorkspaceStore'
import type { OntologyPackage } from '../../api/types'
import OntologyImpactPanel from '../components/OntologyImpactPanel.vue'
import OntologyPackageDialog from '../components/OntologyPackageDialog.vue'

const api = vi.hoisted(() => ({ usage: vi.fn(), impact: vi.fn(), previewPackage: vi.fn(), importPackage: vi.fn(), packageImport: vi.fn() }))
const push = vi.hoisted(() => vi.fn())
vi.mock('../../api/ontologyApi', () => ({ ontologyApi: api })); vi.mock('vue-router', () => ({ useRouter: () => ({ push }) }))
const documentInput = { modelSchema: 'owl-document-v1' as const, syntax: 'FUNCTIONAL' as const, documentText: 'Ontology(<https://example.test/quality>)', imports: [], policy: { version: '1', rules: [] } }
const packageData: OntologyPackage = { packageFormatVersion: 2, name: '质量本体', description: '', source: { ontologyName: '质量本体', version: 1 }, document: documentInput }
const report = { graphId: 'graph-1', sourceRevisionId: 'revision-1', targetRevisionId: 'revision-2', definitionDigest: 'sha256:test', graphVersion: 4, scannedAt: '2026-09-08T01:02:03Z', definitionChangeClass: 'POTENTIALLY_BREAKING', dataConformance: 'VIOLATIONS', scannedEntities: 2, scannedStatements: 3, scannedProposals: 1, affectedEntities: 1, affectedStatements: 1, affectedProposals: 1, detailsTruncated: false, diagnostics: [{ kind: 'ENTITY' as const, id: 'entity-1', code: 'UNKNOWN_ENTITY_TYPE', message: 'missing type' }] }
const flush = async () => { await new Promise(resolve => setTimeout(resolve, 0)); await nextTick() }
function installWorkspace() { setActivePinia(createPinia()); const workspace = useWorkspaceStore(); workspace.currentWorkspaceId = 'workspace-1'; workspace.accessLoaded = true; workspace.currentCapabilities = new Set(['publish:ontology', 'view:ontology'] as never); return workspace }
function mountApp(component: any, props: Record<string, unknown> = {}) { const host = document.createElement('div'); document.body.append(host); const app = createApp(component, props); app.use(ElementPlus).use(createI18n({ legacy: false, locale: 'zh-CN', messages: { 'zh-CN': zh } })).mount(host); return { app, host } }

describe('impact and v2 package flows', () => {
  beforeEach(() => { installWorkspace(); vi.clearAllMocks(); api.usage.mockResolvedValue({ items: [{ graphId: 'graph-1', kbId: 'kb-1', kbName: '工厂知识库', ontologyRevisionId: 'revision-1', ontologyVersion: 1, enabled: true, graphVersion: 4 }], total: 1, page: 1, pageSize: 20 }); api.impact.mockResolvedValue(report); api.previewPackage.mockResolvedValue({ digest: 'sha256:test', name: '质量本体', axiomCount: 1, importCount: 0, violations: [] }); api.importPackage.mockResolvedValue({ operationId: 'op-1', ontologyId: 'ontology-1', draft: { id: 'draft-1' } }); api.packageImport.mockResolvedValue({ operationId: 'op-1', ontologyId: 'ontology-1', draft: { id: 'draft-1' } }) })
  it('cancels usage request when impact becomes disabled', async () => { let signal: AbortSignal | undefined; api.usage.mockImplementation((_scope: string, _id: string, _page: number, _size: number, requestSignal: AbortSignal) => { signal = requestSignal; return new Promise(() => {}) }); const state = reactive({ enabled: true }); const { app, host } = mountApp({ setup: () => () => h(OntologyImpactPanel, { ontologyId: 'ontology-1', targetRevisionId: 'revision-2', enabled: state.enabled }) }); await flush(); state.enabled = false; await flush(); expect(signal?.aborted).toBe(true); app.unmount(); host.remove() })
  it('renders scan diagnostics and routes entity focus', async () => { const { app, host } = mountApp(OntologyImpactPanel, { ontologyId: 'ontology-1', targetRevisionId: 'revision-2', enabled: true }); await flush(); [...host.querySelectorAll('button')].find(button => button.textContent?.includes('分析影响'))?.click(); await flush(); expect(host.textContent).toContain('扫描时间'); expect(host.textContent).toContain('目标本体缺少实体类型'); [...host.querySelectorAll('button')].find(button => button.textContent?.includes('定位'))?.click(); expect(push).toHaveBeenCalledWith({ name: 'SemanticWorkbench', params: { graphId: 'graph-1' }, query: { focus: 'entity-1', kind: 'ENTITY' } }); app.unmount(); host.remove() })
  it('accepts only package v2 document input and sends its raw JSON to preview', async () => { const state = reactive({ open: true }); const { app, host } = mountApp({ setup: () => () => h(OntologyPackageDialog, { modelValue: state.open, 'onUpdate:modelValue': (value: boolean) => { state.open = value } }) }); await flush(); const input = host.querySelector('input[type=file]') as HTMLInputElement; const file = new File([JSON.stringify(packageData)], 'quality.json', { type: 'application/json' }); Object.defineProperty(input, 'files', { configurable: true, value: [file] }); input.dispatchEvent(new Event('change')); await flush(); [...host.querySelectorAll('button')].find(button => button.textContent?.includes('预览'))?.click(); await flush(); expect(api.previewPackage).toHaveBeenCalledWith('workspace-1', JSON.stringify(packageData), expect.any(AbortSignal)); expect((host.querySelector('input[type=text]') as HTMLInputElement)?.value).toBe('质量本体'); app.unmount(); host.remove() })
})
