<template>
  <section class="review-surface">
    <header class="surface-heading"><div><h2>{{ l('整本审核','Whole-book review') }}</h2><p>{{ reviewStatus(view.status) }}</p></div><div class="actions"><el-button type="primary" plain :loading="busy" @click="$emit('refresh')">{{ l('刷新审核','Refresh review') }}</el-button><el-button v-if="canWrite && view.manuscriptRef" type="primary" :disabled="busy || !reviewerReady" @click="$emit('dispatch',view.manuscriptRef)">{{ l('重新审核','Run review') }}</el-button></div><small v-if="canWrite && view.manuscriptRef && !reviewerReady" class="action-reason">{{ l('请先绑定与写作员工不同的审核员。','Bind a reviewer who is distinct from the writer first.') }}</small></header>
    <el-alert v-if="view.reason" :title="reasonLabel(view.reason)" type="warning" :closable="false" />
    <section v-if="view.coverage" class="coverage-card"><div><strong>{{ l('章节覆盖','Chapter coverage') }}</strong><span>{{ view.coverage.chapterIds.length }} / {{ view.coverage.expectedChapterIds.length }}</span></div><progress :value="coveragePercent(view.coverage.chapterIds.length,view.coverage.expectedChapterIds.length)" max="100"/><div><strong>{{ l('技术要求覆盖','Technical requirement coverage') }}</strong><span>{{ view.coverage.requirementIds.length }} / {{ view.coverage.expectedRequirementIds.length }}</span></div><progress :value="coveragePercent(view.coverage.requirementIds.length,view.coverage.expectedRequirementIds.length)" max="100"/><el-tag :type="view.coverage.crossChapterReviewed?'success':'warning'" effect="plain">{{ view.coverage.crossChapterReviewed?l('已完成跨章核查','Cross-chapter check complete'):l('待完成跨章核查','Cross-chapter check pending') }}</el-tag></section>
    <section class="findings-section"><header class="section-heading"><h3>{{ l('审核发现','Findings') }}</h3><div class="filters"><el-select v-model="severity" clearable :placeholder="l('全部严重度','All severities')" aria-label="Severity filter"><el-option v-for="item in severityOptions" :key="item.value" :label="item.label" :value="item.value"/></el-select><el-select v-model="chapter" clearable :placeholder="l('全部章节','All chapters')" aria-label="Chapter filter"><el-option v-for="item in chapters" :key="item.id" :label="item.title" :value="item.id"/></el-select></div></header>
      <p v-if="!filteredFindings.length" class="empty-state">{{ l('当前没有匹配的审核发现','No matching findings') }}</p>
      <article v-for="item in filteredFindings" :key="refKey(item.findingRef)" class="finding-card"><header><div class="finding-tags"><el-tag :type="severityType(item.finding.severity)" effect="plain">{{ severityLabel(item.finding.severity) }}</el-tag><el-tag effect="plain">{{ categoryLabel(item.finding.category) }}</el-tag><el-tag v-if="item.decision!=='OPEN'" effect="plain">{{ decisionLabel(item.decision) }}</el-tag></div><div class="actions"><el-button v-for="evidence in item.finding.evidenceRefs||[]" :key="evidenceKey(evidence)" type="primary" link @click="$emit('evidence',evidence)">{{ l('查看依据','Evidence') }}</el-button></div></header><h4>{{ item.finding.description }}</h4><p v-if="item.finding.recommendation" class="recommendation">{{ item.finding.recommendation }}</p><div class="actions finding-actions"><el-button v-if="canApprove && item.decision==='OPEN'" type="primary" plain :disabled="busy" @click="$emit('fix',item)">{{ l('定向整改','Targeted revision') }}</el-button><el-button v-if="canApprove && item.decision==='OPEN' && canDismiss(item)" type="primary" plain :disabled="busy" @click="$emit('resolve',item,'DISMISS_WITH_EVIDENCE')">{{ l('附证据驳回','Dismiss with evidence') }}</el-button><el-button v-if="canApprove && item.decision==='OPEN' && canDefer(item)" type="primary" plain :disabled="busy" @click="$emit('resolve',item,'DEFER_SUGGESTION')">{{ l('暂不采纳建议','Defer suggestion') }}</el-button><el-button v-for="chapterId in item.finding.chapterRefs||[]" :key="refKey(chapterId)" type="primary" link @click="$emit('chapter',chapterId.id)">{{ chapterTitle(chapterId.id) }}</el-button></div></article>
    </section>
    <section class="todos-section"><header class="section-heading"><h3>{{ l('商务待办','Business items') }}</h3></header><p v-if="!view.humanTodos.length" class="empty-state">{{ l('暂无待办','No open items') }}</p><article v-for="todo in view.humanTodos" :key="refKey(todo.ref)" class="todo-card"><div><h4>{{ todo.title }}</h4><p>{{ todoStatus(todo) }}</p></div><el-tag :type="todo.impactClassification==='UNCLASSIFIED'?'warning':'info'" effect="plain">{{ impactLabel(todo) }}</el-tag><div class="actions"><el-button v-if="canApprove && todo.impactClassification!=='CLASSIFIED'" type="primary" plain :disabled="busy" @click="$emit('classify',todo)">{{ l('判断技术影响','Classify impact') }}</el-button><el-button v-if="canResolveTodo && todo.status==='OPEN'" type="primary" plain :disabled="busy" @click="$emit('resolve-todo',todo)">{{ l('标记已处理','Resolve item') }}</el-button><el-button v-for="evidence in todo.evidenceRefs||[]" :key="evidenceKey(evidence)" type="primary" link @click="$emit('evidence',evidence)">{{ l('查看依据','Evidence') }}</el-button></div></article></section>
  </section>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import type { BiddingHumanTodo, BiddingReviewFinding, BiddingReviewView, Ref } from '../api/types'
const props=defineProps<{view:BiddingReviewView;chapters:{id:string;title:string}[];canWrite:boolean;canApprove:boolean;canResolveTodo:boolean;reviewerReady:boolean;busy?:boolean}>()
defineEmits<{refresh:[];dispatch:[Ref];fix:[BiddingReviewFinding];resolve:[BiddingReviewFinding,'DISMISS_WITH_EVIDENCE'|'DEFER_SUGGESTION'];classify:[BiddingHumanTodo];'resolve-todo':[BiddingHumanTodo];evidence:[Record<string,unknown>];chapter:[string]}>()
const {locale}=useI18n(),l=(zh:string,en:string)=>String(locale.value).startsWith('zh')?zh:en
const severity=ref(''),chapter=ref(''),severityOptions=computed(()=>[...new Set(props.view.findings.map(item=>item.finding.severity).filter((x):x is string=>!!x))].map(value=>({value,label:severityLabel(value)})))
const filteredFindings=computed(()=>props.view.findings.filter(item=>(!severity.value||item.finding.severity===severity.value)&&(!chapter.value||item.finding.chapterRefs?.some(ref=>ref.id===chapter.value))))
const chapters=computed(()=>props.chapters)
watch(()=>props.view.manuscriptRef,()=>{severity.value='';chapter.value=''})
function refKey(ref:Ref){return `${ref.kind}:${ref.id}:${ref.version}:${ref.digest}`}
function evidenceKey(value:Record<string,unknown>){return JSON.stringify(value)}
function chapterTitle(id:string){return props.chapters.find(item=>item.id===id)?.title||l('相关章节','Related chapter')}
function coveragePercent(done:number,total:number){return total?Math.min(100,Math.round(done*100/total)):0}
function isMandatoryProof(item:BiddingReviewFinding){return item.finding.category==='MISSING_MANDATORY_PROOF'}
function canDismiss(item:BiddingReviewFinding){return !isMandatoryProof(item)}
function canDefer(item:BiddingReviewFinding){const category=item.finding.category||'',severity=item.finding.severity||'';const blocks=severity==='BLOCKER'||['MISSING_MANDATORY_PROOF','UNANSWERED_TECHNICAL_REQUIREMENT','UNSUPPORTED_COMMITMENT','SOURCE_UNREADABLE','VERSION_CONFLICT'].includes(category);return !blocks&&(severity==='SUGGESTION'||category==='STYLE_SUGGESTION')}
function severityLabel(value?:string){return value==='BLOCKER'||value==='CRITICAL'?l('阻断','Blocker'):value==='MAJOR'?l('重要','Major'):value==='MINOR'?l('一般','Minor'):value==='SUGGESTION'?l('建议','Suggestion'):l('其他','Other')}
function severityType(value?:string){return value==='BLOCKER'||value==='CRITICAL'?'danger':value==='MAJOR'?'warning':'info'}
function categoryLabel(value?:string){return value==='MISSING_MANDATORY_PROOF'?l('缺少强制证明','Mandatory proof missing'):value==='UNANSWERED_TECHNICAL_REQUIREMENT'?l('技术要求未答复','Technical requirement unanswered'):value==='UNSUPPORTED_COMMITMENT'?l('缺少承诺依据','Unsupported commitment'):value==='SOURCE_UNREADABLE'?l('来源不可读','Source unreadable'):value==='VERSION_CONFLICT'?l('版本冲突','Version conflict'):value==='CROSS_CHAPTER_INCONSISTENCY'?l('跨章不一致','Cross-chapter inconsistency'):value==='TECHNICAL_GAP'?l('技术缺口','Technical gap'):value==='STYLE_SUGGESTION'?l('格式建议','Style suggestion'):value==='MANDATORY'?l('强制要求','Mandatory'):value==='TECHNICAL'?l('技术要求','Technical'):value==='COMMERCIAL'?l('商务要求','Commercial'):l('其他类别','Other category')}
function decisionLabel(value:string){return value==='FIX'?l('已发起整改','Revision requested'):value==='DISMISS_WITH_EVIDENCE'?l('已附证据处置','Dismissed with evidence'):value==='DEFER_SUGGESTION'?l('暂不采纳','Deferred'):l('待处理','Open')}
function reviewStatus(value:string){return value==='REVIEWED'?l('整本与跨章审核已完成','Whole-book and cross-chapter review complete'):value==='IN_PROGRESS'?l('审核任务尚未全部完成','Review tasks are still running'):value==='REVIEW_STALE'?l('当前正文版本的审核已失效','Review is stale for the current manuscript'):value==='REVIEW_ACCESS_REVOKED'?l('审核材料权限已变化','Reviewer material access changed'):value==='NOT_ASSEMBLED'?l('请先组装正文','Assemble the manuscript first'):value==='NOT_DISPATCHED'?l('审核尚未派发','Review has not been dispatched'):l('尚未开始审核','Review has not started')}
function reasonLabel(value:string){return value==='REVIEWER_NOT_BOUND'?l('尚未绑定审核员','No reviewer is assigned'):value==='REVIEWER_MUST_DIFFER'?l('审核员必须与写作员工分离','Reviewer must differ from the writer'):l('请刷新后核对当前审核状态','Refresh and inspect the current review state')}
function todoStatus(todo:BiddingHumanTodo){return todo.status==='OPEN'?l('待处理','Open'):l('已处理','Resolved')}
function impactLabel(todo:BiddingHumanTodo){return todo.impactClassification!=='CLASSIFIED'?l('待判断','Unclassified'):todo.affectsTechnical?l('影响技术标','Affects technical proposal'):l('仅商务事项','Business only')}
</script>
<style scoped>
.review-surface{display:grid;gap:24px;min-width:0}.surface-heading,.section-heading,.finding-card>header{display:flex;align-items:center;justify-content:space-between;gap:12px}.surface-heading h2,.section-heading h3{margin:0;font-size:16px;font-weight:600}.surface-heading p{margin:6px 0 0;color:var(--mc-text-secondary)}.action-reason{color:var(--mc-text-secondary);font-size:12px}.coverage-card,.finding-card,.todo-card{display:grid;gap:12px;padding:16px;border:1px solid var(--mc-border);border-radius:6px;background:var(--mc-bg-elevated)}.coverage-card>div{display:flex;justify-content:space-between;gap:8px}.coverage-card>div span,.finding-card p,.todo-card p{color:var(--mc-text-secondary)}.findings-section,.todos-section{display:grid;gap:12px}.filters,.actions,.finding-tags{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.filters :deep(.el-select){width:220px;flex:0 0 220px}.finding-card h4,.todo-card h4{margin:0;font-size:15px}.finding-card p,.todo-card p{margin:0}.empty-state{margin:0;padding:10px 12px;border:1px dashed var(--mc-border);border-radius:6px;color:var(--mc-text-secondary);font-size:13px}.todo-card{grid-template-columns:minmax(0,1fr) auto}.todo-card .actions{grid-column:1/-1}@media(max-width:600px){.surface-heading,.section-heading,.finding-card>header{align-items:flex-start;flex-direction:column}.filters,.filters :deep(.el-select){width:100%;flex:1 1 100%}.todo-card{grid-template-columns:minmax(0,1fr)}.todo-card .actions{justify-content:flex-start}.coverage-card,.finding-card,.todo-card{padding:12px}}
 .coverage-card progress{width:100%;height:8px;accent-color:var(--mc-primary)}
</style>
