<template>
  <section class="outline-workspace">
    <header class="outline-heading"><div><h2>{{ l('技术目录','Technical outline') }}</h2><span v-if="view.baselineRef">{{ l('解析基线','Analysis baseline') }} V{{ view.baselineRef.version }}</span></div><div class="actions"><el-button type="primary" :disabled="!view.baselineRef || !canDispatch || busy" :loading="dispatching" @click="dispatch">{{ l('生成目录候选','Generate outline') }}</el-button><el-button type="primary" plain :disabled="!dirty || !canWrite || busy || !candidate || !view.editExpectedRef" :loading="saving" @click="save">{{ l('保存目录','Save outline') }}</el-button><el-button type="primary" :disabled="!candidate || !canApprove || !canConfirm || dirty || busy" :loading="confirming" @click="confirm">{{ l('确认目录','Confirm outline') }}</el-button></div></header>
    <el-alert v-if="!view.baselineRef" :title="l('请先确认解析基线。','Confirm the analysis baseline first.')" type="info" :closable="false" />
    <el-alert v-else-if="view.dispatchTodo?.status==='TODO'" :title="l('目录待生成：请检查编写员配置后生成目录。','Outline is ready to generate. Check the writer setup, then generate it.')" type="info" :closable="false" />
    <el-alert v-else-if="!canDispatch && !view.candidates.length && !view.confirmed" :title="l('目录生成暂不可用：请配置编写员及所需技能。','Outline generation is unavailable until a writing employee and required skills are configured.')" type="info" :closable="false" />
    <el-alert v-if="error" :title="error" type="error" :closable="false" />
    <div v-if="view.confirmed" class="confirmed-status"><el-tag type="success" effect="plain">{{ l('目录已确认','Outline confirmed') }} · V{{ view.confirmed.ref.version }}</el-tag></div>
    <div v-if="view.candidates.length || view.confirmed" class="outline-layout">
      <nav class="candidate-list" :aria-label="l('目录版本','Outline versions')"><h3>{{ l('目录候选','Outline candidates') }}</h3><button v-for="item in candidates" :key="key(item.ref)" type="button" :class="{selected:key(item.ref)===selectedKey}" @click="select(item)"><span>{{ l('目录候选','Outline candidate') }} V{{ item.ref.version }}</span><el-tag size="small" effect="plain">{{ statusLabel(item.status) }}</el-tag></button></nav>
      <div v-if="candidate" class="outline-editor">
        <div class="outline-tree"><div class="tree-header"><h3>{{ l('章节结构','Chapter structure') }}</h3><el-button type="primary" plain size="small" :disabled="!canWrite || busy" @click="addChapter">{{ l('添加章节','Add chapter') }}</el-button></div>
          <el-tree :data="tree" node-key="id" :props="treeProps" default-expand-all highlight-current @node-click="selectChapter"><template #default="{data}"><span class="tree-node">{{ data.title }}</span></template></el-tree>
        </div>
        <div class="outline-detail"><template v-if="activeChapter"><div class="detail-heading"><h3>{{ activeChapter.title }}</h3><el-button v-if="canWrite" type="danger" plain size="small" :disabled="busy" @click="removeChapter(activeChapter.id)">{{ l('移除章节','Remove chapter') }}</el-button></div><el-form label-position="top"><el-form-item :label="l('章节标题','Chapter title')"><el-input v-model="activeChapter.title" maxlength="240" :disabled="!canWrite || busy" /></el-form-item><el-form-item :label="l('写作要求','Writing instructions')"><el-input v-model="activeChapter.instructions" type="textarea" :rows="5" maxlength="5000" :disabled="!canWrite || busy" /></el-form-item></el-form><el-tag v-if="activeChapter.mandatoryOutlineRefs?.length" effect="plain">{{ l('已关联强制目录项','Mandatory outline items mapped') }} · {{ activeChapter.mandatoryOutlineRefs.length }}</el-tag><el-tag v-if="activeChapter.requirementRefs?.length" effect="plain">{{ l('已覆盖技术要求','Technical requirements covered') }} · {{ activeChapter.requirementRefs.length }}</el-tag></template><el-empty v-else :description="l('选择一个章节','Select a chapter')" /></div>
        <section class="unmapped"><h3>{{ l('尚未映射的必需项','Unmapped mandatory items') }}</h3><ul v-if="candidate.payload.unmappedItems?.length"><li v-for="(item,index) in candidate.payload.unmappedItems" :key="index">{{ itemText(item) }}</li></ul><p v-else>—</p></section>
        <ul v-if="candidate.payload.warnings?.length" class="warnings"><li v-for="(item,index) in candidate.payload.warnings" :key="index">{{ item }}</li></ul>
      </div>
    </div>
    <el-empty v-else-if="view.baselineRef" :description="l('尚无目录候选','No outline candidates yet')" />
  </section>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import type { OutlineChapter, OutlineRevision, OutlineView, Ref } from '../api/types'
import { operationId } from '../shared/state'
type CommandRequest={action:string;payload:Record<string,unknown>;expected:Ref}
const props=defineProps<{view:OutlineView;projectRef:Ref;savedRef?:Ref;clearToken?:number;canWrite:boolean;canApprove:boolean;canDispatch:boolean;busy?:boolean;dispatching?:boolean;saving?:boolean;confirming?:boolean;error?:string}>()
const emit=defineEmits<{command:[CommandRequest]}>()
const {locale}=useI18n(),l=(zh:string,en:string)=>String(locale.value).startsWith('zh')?zh:en
const candidates=computed(()=>[...(props.view.confirmed?[props.view.confirmed]:[]),...props.view.candidates])
const emptyDraft={chapters:[] as OutlineChapter[],unmappedItems:[] as Record<string,unknown>[],warnings:[] as string[]}
const selectedKey=ref(''),candidate=ref<OutlineRevision>(),draft=ref<{chapters:OutlineChapter[];unmappedItems:Record<string,unknown>[];warnings:string[]}>(emptyDraft),initial=ref(JSON.stringify(emptyDraft)),activeId=ref('')
const busy=computed(()=>!!props.busy),error=computed(()=>props.error||''),dirty=computed(()=>JSON.stringify(draft.value)!==initial.value)
const treeProps={label:'title',children:'children'}
const tree=computed(()=>{const rows=[...draft.value.chapters].sort((a,b)=>a.order-b.order).map(item=>({...item,children:[] as OutlineChapter[]}));const index=new Map(rows.map(item=>[item.id,item]));const roots:OutlineChapter[]=[];for(const row of rows){const parent=row.parentId?index.get(row.parentId):undefined;if(parent)parent.children!.push(row);else roots.push(row)}return roots})
const activeChapter=computed(()=>draft.value.chapters.find(item=>item.id===activeId.value))
const canConfirm=computed(()=>!!candidate.value&&candidate.value.status==='CANDIDATE')
const pendingSavedRef=ref<Ref>()
watch(()=>props.savedRef,value=>{if(value){pendingSavedRef.value=value;selectSavedCandidate()}},{immediate:true})
watch(()=>props.clearToken,()=>{if(props.clearToken){candidate.value=undefined;selectedKey.value='';draft.value={chapters:[],unmappedItems:[],warnings:[]};initial.value=JSON.stringify(draft.value);activeId.value='';pendingSavedRef.value=undefined}})
watch(candidates,items=>{if(selectSavedCandidate())return;if(!items.length){if(!dirty.value){candidate.value=undefined;selectedKey.value=''}return}const found=items.find(item=>key(item.ref)===selectedKey.value);if(found&&candidate.value&&key(candidate.value.ref)===key(found.ref)){candidate.value=found;if(!dirty.value){draft.value=payloadDraft(found);initial.value=JSON.stringify(draft.value)}return}if(!candidate.value||!dirty.value)select(found||items[0]!)},{immediate:true})
function key(ref:Ref){return `${ref.kind}:${ref.id}:${ref.version}:${ref.digest}`}
function payloadDraft(item:OutlineRevision){return {chapters:(item.payload.chapters||[]).map(chapter=>({mandatoryOutlineRefs:[],requirementRefs:[],scoringRefs:[],materialRefs:[],...chapter})),unmappedItems:JSON.parse(JSON.stringify(item.payload.unmappedItems||[])),warnings:[...(item.payload.warnings||[])]}}
function select(item:OutlineRevision){if(dirty.value&&candidate.value&&key(candidate.value.ref)!==key(item.ref))return;candidate.value=item;selectedKey.value=key(item.ref);draft.value=payloadDraft(item);initial.value=JSON.stringify(draft.value);activeId.value=draft.value.chapters[0]?.id||''}
function selectSavedCandidate(){const acknowledged=pendingSavedRef.value;if(!acknowledged)return false;const saved=candidates.value.find(item=>key(item.ref)===key(acknowledged));if(!saved)return false;candidate.value=saved;selectedKey.value=key(saved.ref);draft.value=payloadDraft(saved);initial.value=JSON.stringify(draft.value);activeId.value=draft.value.chapters[0]?.id||'';pendingSavedRef.value=undefined;return true}
function statusLabel(status:string){return status==='CANDIDATE'?l('待确认','Candidate'):status==='STALE'?l('已失效','Outdated'):status==='CONFIRMED'?l('已确认','Confirmed'):l('不可用','Unavailable')}
function itemText(item:Record<string,unknown>){return [item.title,item.text,item.description,item.reason].filter(value=>typeof value==='string'&&value.trim()).join(' · ')||l('待映射项','Unmapped item')}
function selectChapter(value:OutlineChapter){activeId.value=value.id}
function chapterArrays(chapter:OutlineChapter):OutlineChapter{return {mandatoryOutlineRefs:[],requirementRefs:[],scoringRefs:[],materialRefs:[],...chapter}}
function addChapter(){const id=`chapter-${operationId()}`;const next:OutlineChapter=chapterArrays({id,parentId:null,order:draft.value.chapters.length+1,title:l('新章节','New chapter'),instructions:''});draft.value.chapters.push(next);activeId.value=id}
function removeChapter(id:string){const removed=new Set([id]);let changed=true;while(changed){changed=false;for(const chapter of draft.value.chapters)if(chapter.parentId&&removed.has(chapter.parentId)&&!removed.has(chapter.id)){removed.add(chapter.id);changed=true}}draft.value.chapters=draft.value.chapters.filter(item=>!removed.has(item.id));activeId.value=draft.value.chapters[0]?.id||''}
function dispatch(){if(!props.view.baselineRef||!props.canDispatch)return;emit('command',{action:'DISPATCH_OUTLINE',expected:props.view.baselineRef,payload:{}})}
function save(){if(!candidate.value||!props.canWrite||!dirty.value||!props.view.editExpectedRef)return;emit('command',{action:'SAVE_OUTLINE',expected:props.view.editExpectedRef,payload:{payload:{schemaVersion:'1',chapters:draft.value.chapters.map(chapterArrays),unmappedItems:draft.value.unmappedItems,warnings:draft.value.warnings}}})}
function confirm(){if(!candidate.value||!props.canApprove||!canConfirm.value||dirty.value||!props.view.editExpectedRef)return;emit('command',{action:'CONFIRM_OUTLINE',expected:props.view.editExpectedRef,payload:{outlineRef:candidate.value.ref}})}
defineExpose({isDirty:()=>dirty.value,clearSensitiveDraft:()=>{candidate.value=undefined;selectedKey.value='';draft.value={chapters:[],unmappedItems:[],warnings:[]};initial.value=JSON.stringify(draft.value);activeId.value='';pendingSavedRef.value=undefined}})
</script>
<style scoped>
.outline-workspace{display:grid;gap:14px;min-width:0}.outline-heading,.outline-heading>div,.actions,.tree-header,.detail-heading{display:flex;align-items:center;justify-content:space-between;gap:8px}.outline-heading h2{margin:0;font-size:18px}.outline-heading span{color:var(--mc-text-secondary);font-size:13px}.outline-layout{display:grid;grid-template-columns:220px minmax(0,1fr);gap:16px;min-width:0}.candidate-list{display:grid;align-content:start;gap:6px;border-right:1px solid var(--mc-border-light);padding-right:12px}.candidate-list h3,.tree-header h3,.detail-heading h3,.unmapped h3{font-size:14px;margin:0 0 4px}.candidate-list button{display:flex;justify-content:space-between;align-items:center;gap:8px;text-align:left;padding:8px;border:1px solid var(--mc-border);border-radius:4px;background:var(--mc-bg-elevated);color:var(--mc-text-primary);cursor:pointer}.candidate-list button.selected{border-color:var(--mc-primary);background:var(--mc-bg-muted)}.outline-editor{display:grid;grid-template-columns:minmax(220px,32%) minmax(0,1fr);gap:12px;min-width:0}.outline-tree,.outline-detail,.unmapped{min-width:0;border:1px solid var(--mc-border);border-radius:6px;padding:12px;background:var(--mc-bg-elevated)}.tree-header{margin-bottom:8px}.tree-node{display:block;white-space:normal;overflow-wrap:anywhere;line-height:1.4}.outline-tree :deep(.el-tree-node__content){height:auto;min-height:26px;align-items:flex-start;padding-top:4px;padding-bottom:4px}.outline-tree :deep(.el-tree-node__label){white-space:normal;overflow-wrap:anywhere;line-height:1.4}.outline-tree :deep(.el-tree-node__expand-icon){margin-top:3px}.confirmed-status{min-height:20px}.outline-detail{min-height:260px}.detail-heading{margin-bottom:8px}.unmapped{grid-column:1/-1}.unmapped ul,.warnings{margin:8px 0 0;padding-left:20px}.unmapped p{margin:8px 0;color:var(--mc-text-secondary)}.warnings{grid-column:1/-1;color:var(--mc-text-secondary);font-size:13px}.el-tag{margin-right:6px}.el-button:focus-visible,.candidate-list button:focus-visible{outline:2px solid var(--mc-primary);outline-offset:2px}@media(max-width:900px){.outline-heading{align-items:flex-start;flex-direction:column}.outline-heading .actions{flex-wrap:wrap}.outline-layout{grid-template-columns:1fr}.candidate-list{border-right:0;border-bottom:1px solid var(--mc-border-light);padding:0 0 12px}.outline-editor{grid-template-columns:1fr}}
</style>
