<template>
  <section class="artifact-surface"><header class="surface-heading"><h2>{{ l('成果文件','Deliverables') }}</h2><div class="actions"><el-button type="primary" plain :loading="loading" @click="$emit('refresh')">{{ l('刷新文件','Refresh files') }}</el-button></div></header>
    <section class="template-card"><div><strong>{{ l('固定模板','Fixed template') }}</strong><span v-if="template">{{ l('技术标模板 V1','Technical proposal v1') }} · DOCX</span><span v-else>{{ l('尚未准备','Not prepared') }}</span></div><div class="actions"><el-tag v-if="previewOnly" type="warning" effect="plain">{{ l('仅供内部预览','Internal preview only') }}</el-tag><el-tag v-else-if="prepared" type="success" effect="plain">{{ l('已固定版本','Pinned') }}</el-tag><el-button v-if="!template" type="primary" plain :disabled="busy || !canWrite" :loading="busy" @click="$emit('prepare','preview')">{{ l('准备内部预览','Prepare internal preview') }}</el-button><el-button v-if="!prepared" type="primary" plain :disabled="busy || !canWrite" :loading="busy" @click="$emit('prepare','candidate')">{{ l('校验正式格式','Validate formal format') }}</el-button></div></section>
    <el-alert v-if="!artifacts.length" :title="l('尚无生成文件','No generated files yet')" type="info" :closable="false" />
    <article v-for="artifact in artifacts" :key="artifact.artifactId" class="artifact-card"><header><div><h3>{{ artifact.filename || l('技术标文件.docx','Technical proposal.docx') }}</h3><p>{{ artifact.mode==='preview'?l('预览文件','Preview'):artifact.status==='APPROVED'?l('正式审定文件','Approved formal file'):l('待审定候选','Candidate for approval') }} · {{ sizeLabel(artifact.byteSize) }}</p></div><el-tag :type="statusType(artifact.status)" effect="plain">{{ statusLabel(artifact.status) }}</el-tag></header><p v-if="artifact.status==='PREVIEW' && artifact.checks?.previewHeadingLevelsAdjusted" class="preview-warning">{{ l(`已将 ${artifact.checks.previewHeadingLevelsAdjusted} 处四级及更深标题调整为三级，仅供核对内容。`,`Adjusted ${artifact.checks.previewHeadingLevelsAdjusted} deep headings to level 3 for content inspection.`) }}</p><div class="actions"><el-button v-if="artifact.status==='CANDIDATE'" type="primary" plain :disabled="busy" @click="$emit('download',artifact,'candidate')">{{ l('下载检查','Download and inspect') }}</el-button><el-button v-if="artifact.status==='PREVIEW'" type="primary" plain :disabled="busy" @click="$emit('download',artifact,'preview')">{{ l('下载预览','Download preview') }}</el-button><el-button v-if="artifact.status==='CANDIDATE' && canApprove" type="primary" :disabled="busy" @click="$emit('approval-context',artifact)">{{ l('审定此文件','Approve this file') }}</el-button><el-button v-if="artifact.formalAvailable || artifact.status==='APPROVED'" type="primary" plain :disabled="busy || !artifact.formalAvailable" @click="$emit('download',artifact,'formal')">{{ l('下载正式文件','Download formal file') }}</el-button></div><details><summary>{{ l('版本详情','Version details') }}</summary><dl><template v-if="artifact.manuscriptRef"><dt>{{ l('正文版本','Manuscript version') }}</dt><dd>V{{ artifact.manuscriptRef.version }}</dd></template><template v-if="artifact.templateRef"><dt>{{ l('模板版本','Template version') }}</dt><dd>V{{ artifact.templateRef.version }}</dd></template><template v-if="artifact.formatRef"><dt>{{ l('格式版本','Format version') }}</dt><dd>V{{ artifact.formatRef.version }}</dd></template><template v-if="artifact.digest"><dt>{{ l('文件摘要','File digest') }}</dt><dd>{{ artifact.digest }}</dd></template></dl></details></article>
    <section class="generate-card"><h3>{{ l('生成文件','Generate a file') }}</h3><div class="actions"><el-button type="primary" plain :disabled="busy || !canWrite || !template" @click="$emit('generate','preview')">{{ l('生成内部预览','Generate internal preview') }}</el-button><el-button type="primary" :disabled="busy || !canWrite || !prepared" @click="$emit('generate','candidate')">{{ l('生成待审定文件','Generate candidate') }}</el-button></div><p v-if="previewOnly">{{ l('此预览稿可能不符合招标文件格式要求，不能用于审定或正式交付。','This preview may not meet tender formatting requirements and cannot be approved or formally delivered.') }}</p><p v-else-if="!prepared">{{ l('先准备并固定模板版本，再生成文件。','Prepare and pin the template before generating a file.') }}</p></section>
  </section>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { ArtifactMetadata, ExportTemplate } from '../api/types'
defineEmits<{refresh:[];prepare:['preview'|'candidate'];generate:['preview'|'candidate'];download:[ArtifactMetadata,'candidate'|'preview'|'formal'];'approval-context':[ArtifactMetadata]}>()
const props=defineProps<{templates:ExportTemplate[];artifacts:ArtifactMetadata[];loading:boolean;busy:boolean;canWrite:boolean;canApprove:boolean}>()
const {locale}=useI18n(),l=(zh:string,en:string)=>String(locale.value).startsWith('zh')?zh:en
const template=computed(()=>props.templates.find(item=>(item.status==='PREPARED'||item.status==='PREVIEW_ONLY')&&item.ref&&item.formatRef))
const prepared=computed(()=>template.value?.status==='PREPARED'),previewOnly=computed(()=>template.value?.status==='PREVIEW_ONLY')
function statusLabel(value:string){return value==='APPROVED'?l('已审定','Approved'):value==='CANDIDATE'?l('待审定','Candidate'):value==='PREVIEW'?l('预览','Preview'):value==='STALE'?l('版本失效','Stale'):l('处理中','Processing')}
function statusType(value:string){return value==='APPROVED'?'success':value==='STALE'?'danger':value==='PREVIEW'?'info':'warning'}
function sizeLabel(value?:number){return value?`${(value/1024).toFixed(0)} KB`:''}
</script>
<style scoped>
.artifact-surface{display:grid;gap:24px;min-width:0}.surface-heading,.artifact-card>header{display:flex;align-items:center;justify-content:space-between;gap:12px}.surface-heading h2,.artifact-card h3,.generate-card h3{margin:0;font-size:16px;font-weight:600}.artifact-card p,.generate-card p{margin:6px 0 0;color:var(--mc-text-secondary)}.template-card,.artifact-card,.generate-card{display:grid;gap:12px;padding:16px;border:1px solid var(--mc-border);border-radius:6px;background:var(--mc-bg-elevated)}.template-card{grid-template-columns:1fr auto}.template-card>div{display:grid;gap:5px}.template-card span{color:var(--mc-text-secondary)}.actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.artifact-card>header>div{min-width:0}.artifact-card h3{overflow-wrap:anywhere;font-size:16px}.artifact-card details{border-top:1px solid var(--mc-border-light);padding-top:10px}.artifact-card summary{cursor:pointer;color:var(--mc-primary)}.artifact-card dl{display:grid;grid-template-columns:max-content minmax(0,1fr);gap:8px 16px;font-size:12px}.artifact-card dt{color:var(--mc-text-secondary)}.artifact-card dd{margin:0;overflow-wrap:anywhere}.generate-card{margin-top:4px}@media(max-width:600px){.surface-heading,.artifact-card>header{align-items:flex-start;flex-direction:column}.template-card{grid-template-columns:minmax(0,1fr)}.actions :deep(.el-button){margin:0}.template-card,.artifact-card,.generate-card{padding:12px}}
.artifact-surface :deep(.el-alert--info.is-light){background-color:var(--mc-bg-elevated);color:var(--mc-text-secondary);border:1px dashed var(--mc-border)}.artifact-surface :deep(.el-alert--info.is-light .el-alert__title){color:inherit}
.preview-warning{margin:0;color:var(--mc-warning,#b7791f);font-size:12px}
</style>
