<script setup lang="ts">
import { ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useStatementReview } from './useStatementReview'
import { graphQueryApi } from '../api/graphQueryApi'
import { useSemanticScope } from '../shared/useSemanticScope'
import type { SemanticEntity } from '../api/types'
import { statementLabel } from './statementLabel'
import type { Statement } from '../api/workbenchTypes'
const props = defineProps<{ graphId: string; statement: Statement | null; canReview: boolean; entities?: SemanticEntity[] }>(); const emit = defineEmits<{ close: []; saved: []; evidence: [id: string] }>(); const { t, te, locale } = useI18n(); const { begin } = useSemanticScope(); const { current, busy, error, confirm } = useStatementReview(() => props.graphId); const reason = ref(''); const history = ref<Statement[]>([]); const historyError = ref('')
function statusName(status: string) { const key = `semantic.w.states.${status}`; return te(key) ? t(key) : status }; function entityName(id: string) { return props.entities?.find(e => e.id === id)?.displayName ?? id }
watch(() => props.statement, async value => { current.value = value; reason.value = ''; history.value = []; historyError.value = ''; const run = begin(); if (value && props.canReview) try { const result = await graphQueryApi.history(run.id, props.graphId, value.id, run.signal); if (run.current()) history.value = result.revisions } catch (e) { if (run.current()) historyError.value = (e as Error).message } }, { immediate: true })
async function review(action: string) {
  if (!await confirm(action, reason.value)) return
  const run = begin(); historyError.value = ''
  try { const result = await graphQueryApi.history(run.id, props.graphId, current.value!.id, run.signal); if (run.current()) history.value = result.revisions }
  catch (e) { if (run.current()) historyError.value = (e as Error).message }
  emit('saved')
}
</script>
<template><el-drawer size="min(620px, 100vw)" :model-value="!!statement" :title="t('semantic.w.review')" @close="emit('close')"><template v-if="current"><p class="metadata">{{ current.id }} · r{{ current.revision }} · {{ statusName(current.reviewStatus) }} · {{ statusName(current.supportStatus) }}</p><p class="metadata">{{ t('semantic.w.ontologyRevision') }}: {{ current.ontologyRevisionId }}</p><h3>{{ entityName(current.subjectId) }}</h3><p>{{ statementLabel(current, entities ?? [], locale) }}</p><details><summary>{{ locale.startsWith('zh') ? '查看技术详情' : 'Technical details' }}</summary><pre class="assertion">{{ current.assertion?.functionalSyntax ?? 'Assertion payload unavailable' }}</pre><p v-if="current.assertion?.kind">{{ current.assertion.kind }} · {{ current.assertion.signatureIris.join(', ') }}</p></details><p>{{ current.validityKind === 'UNKNOWN' ? t('semantic.w.unknown') : t('semantic.w.interval') }} · {{ current.validFrom ?? '—' }} → {{ current.validTo ?? '—' }}</p><el-button v-for="id in current.evidenceIds" :key="id" @click="emit('evidence', id)">{{ t('semantic.w.evidence') }} · {{ id }}</el-button><template v-if="canReview"><el-input v-model="reason" type="textarea" :placeholder="t('semantic.w.reason')" /><el-button v-if="current.reviewStatus === 'PROPOSED'" :disabled="busy || !reason.trim()" @click="review('ACCEPT')">{{ t('semantic.w.accept') }}</el-button><el-button v-if="current.reviewStatus === 'PROPOSED'" :disabled="busy || !reason.trim()" @click="review('REJECT')">{{ t('semantic.w.reject') }}</el-button><el-button v-if="current.reviewStatus === 'ACCEPTED'" :disabled="busy || !reason.trim()" @click="review('RETRACT')">{{ t('semantic.w.retract') }}</el-button></template><el-alert v-if="error" :title="error.code" :description="error.message" type="error" :closable="false" /><template v-if="canReview"><h3>{{ t('semantic.w.history') }}</h3><el-alert v-if="historyError" :title="historyError" type="error" /><div v-for="revision in history" :key="revision.revision"><p>r{{ revision.revision }} · {{ statusName(revision.reviewStatus) }} · {{ statusName(revision.supportStatus) }} · {{ statementLabel(revision, entities ?? [], locale) }}</p></div></template></template></el-drawer></template>
<style scoped>.metadata { color: var(--mc-text-secondary); font-size: 12px; }.assertion { white-space: pre-wrap; overflow-wrap: anywhere; padding: 12px; background: var(--mc-bg-elevated); border: 1px solid var(--mc-border); }p, h3 { overflow-wrap: anywhere; } p { margin: 10px 0; line-height: 1.6; } h3 { margin: 18px 0 10px; font-weight: 600; } details { margin: 12px 0; } :deep(.el-textarea) { margin: 12px 0; } :deep(.el-button) { white-space: normal; height: auto; min-height: 32px; margin: 4px; }</style>
