<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { extractionApi, type ExtractionCapabilities, type ExtractionTask } from '../api/extractionApi'
import { sourceApi } from '../api/sourceApi'
import type { DocumentView, SemanticEntity } from '../api/types'
import { useSemanticScope } from '../shared/useSemanticScope'
import { useExtractionTask } from './useExtractionTask'
import ExtractionTaskPanel from './ExtractionTaskPanel.vue'
import SuggestionReviewPanel from './SuggestionReviewPanel.vue'
const props = defineProps<{ graphId: string; knowledgeBaseId: string; document?: DocumentView; entities: SemanticEntity[] }>(); const emit = defineEmits<{ submitted: [id: string] }>(); const { t } = useI18n(); const route = useRoute(); const router = useRouter(); const { workspace } = useSemanticScope(); const ws = computed(() => workspace.currentWorkspaceId ?? ''); const taskId = ref(typeof route.query.extractionTask === 'string' ? route.query.extractionTask : ''); const { task, suggestions, loading, error: taskError, refresh } = useExtractionTask(ws, computed(() => props.graphId), taskId); const capabilities = ref<ExtractionCapabilities | null>(null); const materials = ref<{ id: string; title: string }[]>([]); const history = ref<ExtractionTask[]>([]); const source = ref(''); const model = ref(''); const selectedId = ref(''); const busy = ref(false); const error = ref(''); let controller = new AbortController(); let epoch = 0; const selected = computed(() => suggestions.value.find(item => item.id === selectedId.value)); const actions = new Map<string, string>(); function stableAction(key: string) { if (!actions.has(key)) actions.set(key, crypto.randomUUID()); return actions.get(key)! }
async function setup() { const current = ++epoch; controller.abort(); controller = new AbortController(); try { const cap = await extractionApi.capabilities(ws.value, props.graphId, controller.signal); if (current !== epoch) return; capabilities.value = cap; const [items, previous] = await Promise.all([cap.enabled ? sourceApi.materials(ws.value, props.knowledgeBaseId, controller.signal) : Promise.resolve([]), extractionApi.list(ws.value, props.graphId, 1, controller.signal)]); if (current === epoch) { materials.value = items; history.value = previous.items } } catch (e) { if (current === epoch) error.value = (e as Error).message } }
watch(() => [ws.value, props.graphId], () => { selectedId.value = ''; taskId.value = typeof route.query.extractionTask === 'string' ? route.query.extractionTask : ''; void setup() }, { immediate: true, flush: 'sync' }); watch(suggestions, rows => { if (!rows.some(item => item.id === selectedId.value)) selectedId.value = rows[0]?.id ?? '' }); onBeforeUnmount(() => { epoch++; controller.abort() })
async function selectTask(id: string) { taskId.value = id; selectedId.value = ''; await router.replace({ query: { ...route.query, extractionTask: id || undefined } }) }
async function start() { if (busy.value || !source.value || !model.value) return; const current = epoch; busy.value = true; error.value = ''; const operationId = stableAction(`start:${props.graphId}:${source.value}:${model.value}`); try { const result = await extractionApi.start(ws.value, props.graphId, { sourceRef: source.value, modelConfigId: model.value, operationId }, controller.signal); if (current === epoch) { history.value = [result, ...history.value.filter(item => item.id !== result.id)]; actions.delete(`start:${props.graphId}:${source.value}:${model.value}`); await selectTask(result.id) } } catch (e) { if (current === epoch) error.value = (e as Error).message } finally { if (current === epoch) busy.value = false } }
async function action(kind: 'cancel' | 'retry') { if (!task.value || busy.value) return; busy.value = true; try { await extractionApi[kind](ws.value, props.graphId, task.value.id, stableAction(`${kind}:${task.value.id}:${task.value.version}`), controller.signal); await refresh() } catch (e) { error.value = (e as Error).message } finally { busy.value = false } }
</script>
<template><section class="extraction-wizard"><h3>{{ t('semantic.extraction.title') }}</h3><el-alert v-if="error || taskError" :title="error || taskError" type="error" :closable="false" /><el-alert v-if="capabilities && !capabilities.enabled" :title="t('semantic.extraction.disabled')" type="info" :closable="false" /><details v-if="capabilities?.enabled" :open="!taskId" class="new-task"><summary>{{ t('semantic.extraction.start') }}</summary><el-form label-position="top" :disabled="busy" @submit.prevent="start"><el-form-item :label="t('semantic.extraction.source')"><el-select v-model="source" filterable><el-option v-for="item in materials" :key="item.id" :value="item.id" :label="item.title" /></el-select></el-form-item><el-form-item :label="t('semantic.extraction.model')"><el-select v-model="model"><el-option v-for="item in capabilities.models" :key="item.id" :value="item.id" :label="item.name" /></el-select></el-form-item><p class="metadata">{{ t('semantic.extraction.binding') }} {{ capabilities.ontologyRevisionId }}</p><el-button native-type="submit" type="primary" :loading="busy" :disabled="!source || !model">{{ t('semantic.extraction.start') }}</el-button></el-form></details><div v-if="history.length" class="history"><label>{{ t('semantic.extraction.history') }}<select :value="taskId" @change="selectTask(($event.target as HTMLSelectElement).value)"><option value="">{{ t('semantic.extraction.selectTask') }}</option><option v-for="item in history" :key="item.id" :value="item.id">{{ item.sourceTitle }} · {{ item.status }}</option></select></label></div><ExtractionTaskPanel v-if="task" :task="task" :busy="busy || loading" :enabled="capabilities?.enabled ?? false" @refresh="refresh" @cancel="action('cancel')" @retry="action('retry')" /><p v-if="task?.status === 'SUCCEEDED' && !suggestions.length">{{ t('semantic.extraction.empty') }}</p><template v-if="task && suggestions.length"><label class="suggestion-selector">{{ t('semantic.extraction.suggestions', { count: suggestions.length }) }}<select :value="selectedId" @change="selectedId = ($event.target as HTMLSelectElement).value"><option v-for="item in suggestions" :key="item.id" :value="item.id">{{ item.subjectName }} · {{ item.assertionText ?? '—' }} · {{ item.status }}</option></select></label><SuggestionReviewPanel v-if="selected" :key="`${task.id}:${selected.id}`" :graph-id="graphId" :suggestion="selected" :source-text="task.sourceText ?? ''" :entities="entities" :document="document" @saved="refresh" @submitted="emit('submitted', $event)" /></template></section></template>
<style scoped>h3 { margin: 0 0 8px; } p { color: var(--mc-text-secondary); line-height: 1.7; }.new-task { margin: 16px 0; } summary { cursor: pointer; font-weight: 600; padding: 10px 0; }.metadata { font-size: 12px; overflow-wrap: anywhere; }.history { margin-top: 20px; }label { display: flex; align-items: center; flex-wrap: wrap; gap: 12px; }select { color: var(--mc-text-primary); background: var(--mc-bg-elevated); border: 1px solid var(--mc-border); border-radius: 4px; padding: 9px; max-width: 100%; min-width: 0; }.suggestion-selector select { width: min(100%, 720px); }</style>
