<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate } from 'vue-router'
import { ElMessageBox } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { extractionApi, type ExtractionSuggestion, type SuggestionEdit } from '../api/extractionApi'
import type { DocumentView, SemanticEntity } from '../api/types'
import { useSemanticScope } from '../shared/useSemanticScope'
import { evidenceSelection } from '../review/evidenceSelection'
import { evidenceParts } from './extractionEvidence'
import { semanticError } from '../api/semanticErrors'
const props = defineProps<{ graphId: string; suggestion: ExtractionSuggestion; sourceText: string; entities: SemanticEntity[]; document?: DocumentView }>(); const emit = defineEmits<{ saved: []; submitted: [id: string] }>(); const { t } = useI18n(); const { begin, workspace } = useSemanticScope(); const form = ref<ExtractionSuggestion>(JSON.parse(JSON.stringify(props.suggestion))); const baseline = ref(''); const busy = ref(false); const error = ref(''); const selecting = ref(false); const dirty = computed(() => JSON.stringify(form.value) !== baseline.value); const readOnly = computed(() => form.value.status !== 'OPEN'); const parts = computed(() => form.value.quotes.map(quote => evidenceParts(props.sourceText, quote))); const subjectOptions = computed(() => props.entities.filter(entity => !form.value.subjectIri || entity.iri === form.value.subjectIri)); const targetOptions = computed(() => props.entities.filter(entity => !form.value.targetIri || entity.iri === form.value.targetIri));
watch(() => props.suggestion, value => { form.value = JSON.parse(JSON.stringify(value)); baseline.value = JSON.stringify(form.value); error.value = '' }, { immediate: true }); async function confirmLeave() { if (!dirty.value && !busy.value) return true; try { await ElMessageBox.confirm(t('semantic.leaveWarning'), t('semantic.unsaved'), { confirmButtonText: t('semantic.leave'), cancelButtonText: t('semantic.stay'), type: 'warning' }); return true } catch { return false } }; onBeforeRouteLeave(confirmLeave); onBeforeRouteUpdate(confirmLeave); const unregister = workspace.registerBeforeSwitch(confirmLeave); const unload = (event: BeforeUnloadEvent) => { if (dirty.value || busy.value) { event.preventDefault(); event.returnValue = '' } }; globalThis.addEventListener('beforeunload', unload); onBeforeUnmount(() => { unregister(); globalThis.removeEventListener('beforeunload', unload) }); defineExpose({ confirmLeave }); function selectQuote(event: Event) { const text = event.target as HTMLTextAreaElement; try { form.value.quotes = [evidenceSelection(props.sourceText, text.selectionStart, text.selectionEnd)]; error.value = '' } catch { /* empty selection */ } }
function editPayload(status: string): SuggestionEdit { return { expectedVersion: form.value.version, operationId: crypto.randomUUID(), status, subjectIri: form.value.subjectIri ?? null, subjectTypeIris: form.value.subjectTypeIris ?? [], subjectName: form.value.subjectName, subjectId: form.value.subjectId ?? null, assertionText: form.value.assertionText ?? '', targetIri: form.value.targetIri ?? null, targetTypeIris: form.value.targetTypeIris ?? [], targetName: form.value.targetName ?? null, targetEntityId: form.value.targetEntityId ?? null, validityKind: form.value.validityKind, validFrom: form.value.validFrom, validTo: form.value.validTo, quotes: form.value.quotes } }
function submitOperationId() {
  const key = `semantic:extraction:submit:${props.graphId}:${form.value.id}`
  const existing = sessionStorage.getItem(key)
  if (existing) return existing
  const operationId = form.value.pendingOperationId ?? crypto.randomUUID()
  sessionStorage.setItem(key, operationId)
  return operationId
}
async function save(status = 'OPEN') { if (busy.value || readOnly.value && status === 'OPEN') return; const run = begin(); busy.value = true; error.value = ''; try { const result = await extractionApi.edit(run.id, props.graphId, form.value.id, editPayload(status), run.signal); if (run.current()) { form.value = result; baseline.value = JSON.stringify(result); emit('saved') } } catch (e) { if (run.current()) error.value = semanticError(e).message } finally { if (run.current()) busy.value = false } }
async function submit() { if (busy.value || dirty.value || readOnly.value || !form.value.assertionText?.trim() || !form.value.quotes.length) return; const run = begin(); busy.value = true; try { const result = await extractionApi.submit(run.id, props.graphId, form.value.id, { expectedVersion: form.value.version, operationId: submitOperationId() }, run.signal); if (run.current()) { baseline.value = JSON.stringify(form.value); emit('submitted', result.statementId); emit('saved') } } catch (e) { if (run.current()) error.value = semanticError(e).message } finally { if (run.current()) busy.value = false } }
</script>
<template><div class="review-columns"><section class="source-pane"><h3>{{ t('semantic.w.snapshotText') }}</h3><template v-for="(part, index) in parts" :key="index"><pre v-if="part" class="evidence-text"><span>{{ part.before }}</span><mark>{{ part.quote }}</mark><span>{{ part.after }}</span></pre><el-alert v-else :title="t('semantic.extraction.invalidQuote')" type="error" :closable="false" /></template><el-button v-if="!readOnly" @click="selecting = !selecting">{{ t('semantic.extraction.reselect') }}</el-button><textarea v-if="selecting" :value="sourceText" readonly :aria-label="t('semantic.w.snapshotText')" @select="selectQuote" @mouseup="selectQuote" /></section><el-form label-position="top" :disabled="busy || readOnly" class="suggestion-form" @submit.prevent="save()"><h3>{{ t('semantic.extraction.reviewSuggestion') }}</h3><el-form-item :label="t('semantic.w.subject')"><el-select v-model="form.subjectIri" clearable filterable><el-option v-for="entity in subjectOptions" :key="entity.id" :value="entity.iri" :label="`${entity.displayName} · ${entity.iri}`" /></el-select></el-form-item><el-form-item :label="t('semantic.w.assertion', 'Assertion Functional Syntax')"><el-input v-model="form.assertionText" type="textarea" :rows="8" spellcheck="false" /></el-form-item><el-form-item :label="t('semantic.w.target', 'Target IRI')"><el-select v-model="form.targetIri" clearable filterable><el-option v-for="entity in targetOptions" :key="entity.id" :value="entity.iri" :label="`${entity.displayName} · ${entity.iri}`" /></el-select></el-form-item><el-form-item :label="t('semantic.w.validity')"><el-select v-model="form.validityKind"><el-option value="UNKNOWN" :label="t('semantic.w.unknown')" /><el-option value="INTERVAL" :label="t('semantic.w.interval')" /></el-select></el-form-item><template v-if="form.validityKind === 'INTERVAL'"><el-form-item :label="t('semantic.w.validFrom')"><el-date-picker v-model="form.validFrom" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></el-form-item><el-form-item :label="t('semantic.w.validTo')"><el-date-picker v-model="form.validTo" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></el-form-item></template><el-alert v-for="(diagnostic, index) in form.diagnostics" :key="index" :title="diagnostic" type="warning" :closable="false" /><el-alert v-if="error" :title="error" type="error" :closable="false" /><p v-if="dirty">{{ t('semantic.extraction.saveBeforeSubmit') }}</p><div v-if="!readOnly" class="actions"><el-button native-type="submit" :loading="busy">{{ t('semantic.extraction.saveReview') }}</el-button><el-button type="primary" :disabled="dirty || !form.assertionText?.trim() || !form.quotes.length" @click="submit">{{ t('semantic.extraction.submit') }}</el-button><el-button @click="save('IGNORED')">{{ t('semantic.extraction.ignore') }}</el-button></div><p v-else>{{ form.status }}</p></el-form></div></template>
<style scoped>.review-columns { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 24px; margin-top: 20px; }.source-pane, .suggestion-form { min-width: 0; }.evidence-text, textarea { white-space: pre-wrap; overflow-wrap: anywhere; width: 100%; box-sizing: border-box; padding: 14px; border: 1px solid var(--mc-border); background: var(--mc-bg-elevated); color: var(--mc-text-primary); max-height: 460px; overflow: auto; font: inherit; line-height: 1.8; }textarea { min-height: 280px; margin-top: 12px; }mark { background: var(--el-color-warning-light-7); color: #3d2b0f; }.actions { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 16px; }@media(max-width: 900px) { .review-columns { grid-template-columns: minmax(0, 1fr); } }</style>
